-- ⚠⚠ PAS APPLIQUÉ — GARDÉ AU CAS OÙ (28/08/2026)
-- Mag a d'abord demandé le rappel PAR MAIL, puis a tranché autrement une heure plus
-- tard : « ok fais ça dans ma liste alors ». Le rappel vit donc DANS L'APP, pas dans
-- une boîte mail — voir Ma liste.
-- Tout ce qui avait été créé dans Supabase pour l'essai a été RETIRÉ le jour même
-- (table `rappels_asso`, extensions `pg_cron` et `pg_net` : la base est revenue
-- exactement comme elle était).
-- Ce fichier reste parce que le travail est fait : si elle redemande le mail, il ne
-- manquera qu'un compte d'envoi et sa clé — qu'elle seule peut créer.
--
-- ═══════════════════════════════════════════════════════════════════════════
-- LE RAPPEL PAR MAIL : « il faut les contacter » (Mag, 28/08/2026)
--
--   « Il faut me faire un rappel par mail quand je dois les contacter. »
--
-- Une association dont toutes les dates sont passées n'a plus de programme dans
-- COUSIN. Sa carte le dit à l'écran (« aucune date à venir ») — mais personne ne va
-- regarder une page tous les jours pour vérifier qu'il ne s'y passe rien. C'est
-- exactement ce qu'un rappel doit faire à notre place.
--
-- ⚠ TROIS GARDE-FOUS, et ils comptent plus que l'envoi lui-même :
--   ① UNE FOIS PAR SEMAINE PAR ASSOCIATION, pas une fois par jour. Un rappel qui
--      arrive tous les matins finit dans la corbeille sans être lu — et le jour où
--      il compte vraiment, il y va aussi.
--   ② SANS CLÉ, ÇA NE PLANTE PAS : la fonction rend -1 et ne fait rien. La tâche
--      peut donc être posée AVANT que le compte d'envoi existe.
--   ③ TOUT ENVOI EST JOURNALISÉ (`rappels_asso`). Sans journal, impossible de savoir
--      si un rappel n'est pas parti ou s'il est parti et n'a pas été lu.
--
-- ⚠ LES ACCENTS PASSENT EN BASE64 : le presse-papier vers l'éditeur SQL les abîme
-- (« écrits » → « √©crits »). Seul de l'ASCII transite.
-- ═══════════════════════════════════════════════════════════════════════════

create extension if not exists pg_net;
create extension if not exists pg_cron;

-- LE JOURNAL DES RAPPELS. Aucune policy : personne n'y touche depuis l'app, la
-- fonction y écrit en `security definer`.
create table if not exists public.rappels_asso (
  id        bigint generated by default as identity primary key,
  asso      text not null,
  derniere  date,
  requete   bigint,
  envoye_le timestamptz not null default now()
);
create index if not exists rappels_asso_idx on public.rappels_asso (asso, envoye_le desc);
alter table public.rappels_asso enable row level security;

create or replace function public.rappel_assos_sans_programme()
returns integer
language plpgsql
security definer
set search_path = public, net, vault, extensions
as $fn$
declare
  cle  text;
  dest text;
  a    record;
  n    integer := 0;
  req  bigint;
begin
  select decrypted_secret into cle  from vault.decrypted_secrets where name = 'resend_key'   limit 1;
  select decrypted_secret into dest from vault.decrypted_secrets where name = 'rappel_email' limit 1;
  if cle is null or dest is null then
    return -1;                       -- ni cle ni adresse : on ne fait rien, et on ne casse rien
  end if;

  for a in
    select asso, max(jour) as derniere
      from public.activites
     where coalesce(btrim(asso), '') <> ''
     group by asso
    having max(jour) < current_date
  loop
    if exists (select 1 from public.rappels_asso r
                where r.asso = a.asso
                  and r.envoye_le > now() - interval '7 days') then
      continue;
    end if;

    select net.http_post(
      url     := 'https://api.resend.com/emails',
      headers := jsonb_build_object('Authorization', 'Bearer ' || cle,
                                    'Content-Type',  'application/json'),
      body    := jsonb_build_object(
        'from',    'COUSIN <onboarding@resend.dev>',
        'to',      jsonb_build_array(dest),
        'subject', convert_from(decode('Q09VU0lOIOKAlCA=','base64'),'UTF8') || a.asso || convert_from(decode('IG4nYSBwbHVzIGRlIHByb2dyYW1tZQ==','base64'),'UTF8'),
        'html',    convert_from(decode('PHA+Qm9uam91ciBNYWcsPC9wPjxwPjxiPg==','base64'),'UTF8') || a.asso || convert_from(decode('PC9iPiBuJ2EgcGx1cyBhdWN1bmUgZGF0ZSDDoCB2ZW5pciBkYW5zIENPVVNJTi48YnI+RGVybmnDqHJlIGFjdGl2aXTDqSBlbmNvZMOpZSA6IA==','base64'),'UTF8') || to_char(a.derniere, 'DD/MM/YYYY') || convert_from(decode('LjwvcD48cD5JbCBmYXV0IGxlcyBjb250YWN0ZXIgcG91ciBhdm9pciBsZSBwcm9ncmFtbWUgZHUgbW9pcy48L3A+PHAgc3R5bGU9ImNvbG9yOiM3Nzc7Zm9udC1zaXplOjEzcHgiPlJhcHBlbCBhdXRvbWF0aXF1ZSBkZSBDT1VTSU4uIFRhbnQgcXUnYXVjdW5lIGRhdGUgbidlc3QgZW5jb2TDqWUsIGlsIHJldmllbnQgdW5lIGZvaXMgcGFyIHNlbWFpbmUuPC9wPg==','base64'),'UTF8'))
    ) into req;

    insert into public.rappels_asso(asso, derniere, requete)
    values (a.asso, a.derniere, req);
    n := n + 1;
  end loop;
  return n;
end;
$fn$;

revoke all on function public.rappel_assos_sans_programme() from public, anon, authenticated;

-- TOUS LES MATINS A 6H UTC (8h a Bruxelles en ete, 7h en hiver).
select cron.unschedule('rappel-assos') where exists (select 1 from cron.job where jobname='rappel-assos');
select cron.schedule('rappel-assos', '0 6 * * *', 'select public.rappel_assos_sans_programme();');
