-- ===========================================================================
-- COUSIN -- L'onglet Absences (03/10/2026)
-- Mag : un onglet "Absences" a la place de "Notes", dessin E (planche
-- propositions/absences.html). Nom EN ENTIER, pas de chambre. LAM ou medical.
-- Chaque absence : ses nuits (des dates), et un statut (non justifiee,
-- justifiee, hospitalise).
--
-- POURQUOI : "c'est juste une histoire de decodage pour les chiffres des
-- subventions". Un LAM a 3 nuits doit etre desencode, quel que soit le motif,
-- "sinon on a un probleme avec les subsides".
--
-- QUI : groupes A, B, C -- "les groupes D n'ont absolument pas le droit de voir
-- ca". Meme verrou que les entretiens : peut_voir_entrants() (sql/entrants.sql).
--
-- (Pas d'accents dans ce fichier : l'editeur SQL les abime.)
-- ===========================================================================

create table if not exists public.absences (
  id            bigint generated by default as identity primary key,
  nom           text        not null check (char_length(nom) between 1 and 80),
  lam           boolean     not null default false,
  statut        text        not null default 'nonjust'
                            check (statut in ('nonjust','just','hospit')),
  nuits         date[]      not null default '{}',
  rentre_le     timestamptz, rentre_par     text,
  desencode_le  timestamptz, desencode_par  text,
  ajoute_par    text,
  uid           uuid        not null default auth.uid(),
  cree_le       timestamptz not null default now()
);

alter table public.absences enable row level security;

drop policy if exists abs_lecture on public.absences;
create policy abs_lecture on public.absences for select to authenticated
  using (public.peut_voir_entrants());

drop policy if exists abs_ajout on public.absences;
create policy abs_ajout on public.absences for insert to authenticated
  with check (public.peut_voir_entrants() and uid = auth.uid());

drop policy if exists abs_maj on public.absences;
create policy abs_maj on public.absences for update to authenticated
  using (public.peut_voir_entrants()) with check (public.peut_voir_entrants());

-- Retirer : tout le groupe A, B, C (Mag, 03/10/2026 : pas de "Rentre" ni de
-- "Desencode", "il faut juste pouvoir les retirer" -- une corbeille).
drop policy if exists abs_retirer on public.absences;
create policy abs_retirer on public.absences for delete to authenticated
  using (public.peut_voir_entrants());

-- -- PASSE DANS SUPABASE LE 03/10/2026. Verifie compte par compte (pg_temp.t) :
--   Coordination, Infirmier, Travailleur social : ecrit / voit / retire.
--   Polyvalent : ecriture refusee, ne voit rien. Aucune ligne de test restee.

-- 03/10/2026 : une note sous le nom ("Disparition inquietante faite le 01/10").
alter table public.absences add column if not exists note text
  check (note is null or char_length(note) <= 300);

-- La cle de la porte (les policies ne suffisent pas).
grant select, insert, update, delete on public.absences to authenticated;

-- 03/10/2026 : "derniere mise a jour ... et par qui". Une seule ligne, reecrite apres
-- chaque ecriture (corbeille comprise). Memes droits : A, B, C.
create table if not exists public.absences_maj (
  id int primary key default 1 check (id = 1),
  le timestamptz not null default now(),
  par text);
alter table public.absences_maj enable row level security;
drop policy if exists absmaj_lecture on public.absences_maj;
create policy absmaj_lecture on public.absences_maj for select to authenticated using (public.peut_voir_entrants());
drop policy if exists absmaj_ajout on public.absences_maj;
create policy absmaj_ajout on public.absences_maj for insert to authenticated with check (public.peut_voir_entrants());
drop policy if exists absmaj_maj on public.absences_maj;
create policy absmaj_maj on public.absences_maj for update to authenticated using (public.peut_voir_entrants()) with check (public.peut_voir_entrants());
grant select, insert, update on public.absences_maj to authenticated;
