-- ⚠⚠ ÉCARTÉ LE 08/08/2026, LE JOUR MÊME, PAR MAG : « laissons tomber les
-- accompagnements pour l'instant. Mathilde peut mettre son rappel pour elle-même
-- dans sa liste perso avec une notification. »
--
-- LA TABLE EXISTE dans Supabase (elle a été créée avant qu'elle tranche) mais
-- L'APP NE S'EN SERT PLUS : tout le code a été retiré d'index.html. Ne pas la
-- supprimer — elle est vide, elle ne coûte rien, et l'idée peut revenir.
--
-- CE QUI A ÉTÉ FAIT À LA PLACE, et qui est plus juste : les rappels perso, qui
-- existaient déjà, ont reçu UNE DATE FACULTATIVE. Un rappel daté dort jusqu'à son
-- matin, puis il remonte dans Ma liste et allume la pastille. Pas de nouvelle
-- table, rien de partagé, aucune pression de remplissage sur les éducs — c'est la
-- même raison qui lui avait fait écarter l'agenda des activités en juillet.
--
-- Le fichier reste ici comme trace de la version partagée, avec sa politique
-- « un collègue peut cocher un accompagnement partagé », si on y revient un jour.
-- ═══════════════════════════════════════════════════════════════════════════

-- ═══════════════════════════════════════════════════════════════════════════
-- LES ACCOMPAGNEMENTS — demandé par Mag le 08/08/2026, pour Mathilde
--
--   « Ma collègue Mathilde est éducatrice. Elle doit faire des accompagnements,
--    par exemple, et elle aimerait pouvoir avoir une liste quand elle sait qu'il
--    y a un accompagnement. Elle le note. Comme ça, les accompagnements qu'elle a
--    à faire, elle les voit dans son application et elle a une notification dans
--    sa liste. Ça pourrait aussi être dans l'accueil, par exemple à côté des
--    poubelles et des linges. »
--
-- CE QUE ÇA N'EST PAS : ce n'est pas une nouvelle liste. Un écran « Mes
-- accompagnements » à part serait un troisième endroit où penser à regarder, et
-- c'est exactement comme ça qu'on oublie. Ça atterrit dans MA LISTE DU JOUR, là
-- où elle regarde déjà, et sur l'ACCUEIL le jour même — pas avant.
--
-- ⚠ POURQUOI UNE DATE, ET RIEN D'AUTRE. Les rappels perso existaient déjà. Ce qui
-- leur manquait, c'est un JOUR : sans lui, un rappel reste au même endroit tous
-- les jours, et on cesse de le voir. Avec lui, il remonte tout seul le bon matin.
--
-- ═══ `partage` : ELLE CHOISIT À CHAQUE FOIS (décision de Mag) ═══
-- Privé par défaut. Partagé, l'équipe le voit ET peut le cocher.
-- La raison est le rythme de travail : les éducateurs sont en 4-4 (quatre jours
-- de travail, quatre de repos). Si Mathilde est malade le jour du rendez-vous, un
-- rappel qui ne vit que chez elle ne prévient personne — et c'est quelqu'un
-- d'autre qui perd son rendez-vous. Mais tout n'a pas à être partagé non plus :
-- d'où le choix, à chaque fois, plutôt qu'une règle imposée.
--
-- ⚠ AUCUN NOM DE RÉSIDENT. Des initiales, comme sur les chambres. Et JAMAIS le
-- motif du rendez-vous — médical, justice, mutuelle : ça ne regarde pas l'équipe.
-- La ligne dit qu'il y a un accompagnement, pas de quoi il s'agit.
-- ═══════════════════════════════════════════════════════════════════════════

create table if not exists public.accompagnements (
  id         bigint generated by default as identity primary key,
  quoi       text        not null,              -- « accompagnement au CPAS »
  quand      date        not null,              -- le jour : c'est lui qui fait tout
  heure      text,                              -- « 10:00 », libre
  initiales  text,                              -- 14 caractères max côté app
  ou         text,                              -- le lieu
  partage    boolean     not null default false,
  fait_le    timestamptz,
  fait_par   text,
  uid        uuid        not null default auth.uid(),
  par        text,                              -- le prénom affiché, pour l'équipe
  cree_le    timestamptz not null default now()
);

create index if not exists accompagnements_quand_idx on public.accompagnements (quand);

-- ── QUI PEUT QUOI ────────────────────────────────────────────────────────────
alter table public.accompagnements enable row level security;

-- On voit les siens, et ceux que quelqu'un a choisi de partager.
drop policy if exists accomp_lecture on public.accompagnements;
create policy accomp_lecture on public.accompagnements for select to authenticated
  using (partage or uid = auth.uid());

drop policy if exists accomp_ecriture on public.accompagnements;
create policy accomp_ecriture on public.accompagnements for insert to authenticated
  with check (uid = auth.uid());

-- ⚠ UN COLLÈGUE PEUT COCHER UN ACCOMPAGNEMENT PARTAGÉ, et c'est voulu : partager
-- sans pouvoir reprendre le relais ne servirait à rien. Un accompagnement PRIVÉ,
-- lui, ne se modifie que par la personne qui l'a écrit.
drop policy if exists accomp_maj on public.accompagnements;
create policy accomp_maj on public.accompagnements for update to authenticated
  using (uid = auth.uid() or partage) with check (uid = auth.uid() or partage);

-- Supprimer reste à l'auteur : on peut reprendre le travail de quelqu'un, pas
-- effacer sa ligne.
drop policy if exists accomp_suppr on public.accompagnements;
create policy accomp_suppr on public.accompagnements for delete to authenticated
  using (uid = auth.uid());

-- ── PASSÉ DANS SUPABASE LE 08/08/2026 ────────────────────────────────────────
-- « Success. No rows returned ».
