-- COUSIN — « Ce que l'équipe sait d'un lieu » (Mag, 13/08/2026)
--
-- Sa demande : « je trouve ça chouette qu'on puisse mettre une appréciation des
-- collègues à chaque fois ».
--
-- ⚠ POURQUOI CETTE TABLE EXISTE, ET PAS SEULEMENT UN CHAMP DANS LE CATALOGUE.
-- Le catalogue vit dans le CODE : pour le changer, il faut publier. Or ce qu'on
-- apprend d'un lieu — ils ne prennent plus les hommes seuls, ils ferment à 16 h, le
-- mercredi c'est réservé aux femmes — se découvre sur le terrain, un mardi, par
-- quelqu'un qui n'a pas accès au dépôt. Ça doit pouvoir s'écrire depuis l'app.
--
-- ⚠⚠ IL N'Y A QUE DU POSITIF, ET C'EST UNE DÉCISION D'ELLE (13/08/2026).
-- Je l'avais avertie qu'un avis négatif sur une association NOMMÉE, dans un outil que
-- 35 personnes lisent et qui s'imprime, peut sortir du centre. Sa réponse : « non, on
-- mettra juste en priorité ceux qui sont notés positivement ». Le classement fait donc
-- le travail à la place du pouce baissé — et le risque disparaît avec lui.
-- ⚠ Ceci REMPLACE sa demande du 08/08/2026 (« et aussi ceux qu'on déconseille »).
-- Ne pas rouvrir la colonne sans elle.
--
-- ⚠ AUCUN NOM D'HÉBERGÉ. Règle de la maison, rappelée à l'écran.

create table if not exists public.avis (
  id          bigint generated by default as identity primary key,
  sid         text        not null,              -- la fiche du catalogue
  uid         uuid        not null default auth.uid(),
  auteur_nom  text        not null default '',   -- signé : elle a choisi « signé »
  texte       text        not null default '',
  -- L'étiquette du lieu : jour · nuit · sejour · urgence · orientation.
  -- ⚠ NULL veut dire « on ne sait pas », et c'est une réponse valable — sa règle des
  -- trois états (posée pour le PMR le 13/08). On ne déduit JAMAIS d'un blanc.
  etiquette   text        null,
  cree_le     timestamptz not null default now(),
  constraint avis_etiquette_connue check (
    etiquette is null or etiquette in ('jour','nuit','sejour','urgence','orientation')
  ),
  -- Un avis par personne et par fiche : on modifie le sien, on n'en empile pas dix.
  constraint avis_un_par_personne unique (sid, uid)
);

create index if not exists avis_sid_idx on public.avis (sid);

alter table public.avis enable row level security;

-- LECTURE : tout membre actif. Un avis sert à toute l'équipe, sinon il ne sert à rien.
drop policy if exists avis_lire on public.avis;
create policy avis_lire on public.avis
  for select to authenticated
  using (public.is_active_member());

-- ÉCRIRE : le sien, et seulement si on est actif.
drop policy if exists avis_ecrire on public.avis;
create policy avis_ecrire on public.avis
  for insert to authenticated
  with check (uid = auth.uid() and public.is_active_member());

-- MODIFIER / RETIRER : le sien. L'administration peut retirer (modération).
drop policy if exists avis_modifier on public.avis;
create policy avis_modifier on public.avis
  for update to authenticated
  using (uid = auth.uid()) with check (uid = auth.uid());

drop policy if exists avis_retirer on public.avis;
create policy avis_retirer on public.avis
  for delete to authenticated
  using (uid = auth.uid() or public.is_admin());

-- ⚠ SANS CE GRANT, LES POLICIES NE SUFFISENT PAS : « permission denied ».
-- La leçon a déjà coûté une séance (voir la mémoire « le grant des nouvelles tables »).
grant select, insert, update, delete on public.avis to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- Le temps réel, comme le chantier et les chambres : ce qu'une collègue écrit
-- pendant qu'on regarde doit apparaître sans recharger.
alter table public.avis replica identity full;
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and tablename = 'avis'
  ) then
    alter publication supabase_realtime add table public.avis;
  end if;
end $$;
