-- ═══════════════════════════════════════════════════════════════════════════
-- LA LISTE DU BINÔME — demandée par Mag le 07/10/2026
--
--   « Je souhaiterais travailler en binôme avec Afaf. J'aimerais pouvoir lui
--    donner accès à ma liste. »
--
-- ⚠ CE N'EST PAS « MA LISTE PERSO » PARTAGÉE, et c'est voulu. Ma liste perso vit
-- dans `reglages_perso`, sauvée EN BLOC : « le dernier qui a écrit fait foi ».
-- Deux personnes dessus = l'une efface l'autre en silence. Ici, chaque ligne est
-- une rangée à part : on peut écrire à deux en même temps sans rien perdre.
--
-- `binome_membres` : qui est dans quel binôme (par adresse mail de connexion).
-- `binome`         : le nom du binôme, et c'est aussi le titre de la carte.
-- Ajouter quelqu'un : une ligne de plus dans `binome_membres`, rien d'autre.
-- ═══════════════════════════════════════════════════════════════════════════

create table if not exists public.binome_membres (
  binome text not null,
  email  text not null,
  primary key (binome, email)
);

create table if not exists public.binome_lignes (
  id       bigint generated by default as identity primary key,
  binome   text        not null,
  texte    text        not null,
  chambre  text,
  fait_le  timestamptz,
  fait_par text,
  par      text,
  uid      uuid        not null default auth.uid(),
  cree_le  timestamptz not null default now()
);
create index if not exists binome_lignes_idx on public.binome_lignes (binome, cree_le);

-- security definer : la policy de binome_membres peut s'en servir sans tourner en rond.
create or replace function public.est_du_binome(b text) returns boolean
language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.binome_membres
                 where binome = b and email = lower(auth.jwt()->>'email'));
$$;

alter table public.binome_membres enable row level security;
alter table public.binome_lignes  enable row level security;

drop policy if exists bm_lecture on public.binome_membres;
create policy bm_lecture on public.binome_membres for select to authenticated
  using (public.est_du_binome(binome));

drop policy if exists bl_tout on public.binome_lignes;
create policy bl_tout on public.binome_lignes for all to authenticated
  using (public.est_du_binome(binome)) with check (public.est_du_binome(binome));

-- ⚠ Sans grant : « permission denied » (voir la mémoire du 08/08/2026).
grant select on public.binome_membres to authenticated;
grant select, insert, update, delete on public.binome_lignes to authenticated;

insert into public.binome_membres (binome, email) values
  ('Mag + Afaf', 'grosbalou55@hotmail.com'),
  ('Mag + Afaf', 'magali.contrino@samusocial.be'),
  ('Mag + Afaf', 'afaf.aboulkhir@samusocial.be')
on conflict do nothing;

-- ═══ LES RÉPONSES SOUS UNE LIGNE (Mag, 07/10/2026) ═══
-- « Une réponse sous la ligne, et je veux une notification aussi. »
-- Table à part, et pas une colonne de la ligne : à deux qui répondent en même temps,
-- une colonne réécrite en bloc perdrait une des deux réponses.
create table if not exists public.binome_reponses (
  id       bigint generated by default as identity primary key,
  ligne_id bigint      not null references public.binome_lignes(id) on delete cascade,
  binome   text        not null,
  texte    text        not null,
  par      text,
  uid      uuid        not null default auth.uid(),
  cree_le  timestamptz not null default now()
);
create index if not exists binome_reponses_idx on public.binome_reponses (ligne_id);
alter table public.binome_reponses enable row level security;
drop policy if exists br_tout on public.binome_reponses;
create policy br_tout on public.binome_reponses for all to authenticated
  using (public.est_du_binome(binome)) with check (public.est_du_binome(binome));
grant select, insert, update, delete on public.binome_reponses to authenticated;
