-- ===========================================================================
-- LES ENTRANTS -- demande de Mag, 18/09/2026
--
--   "Souvent on a des entrants. A chaque entrant on doit absolument faire un
--    entretien, mais on ne sait jamais qui, quoi et quand. Propose une solution
--    qui exclut totalement le groupe D. Et oui, on va pouvoir mettre des noms."
--   Puis : "il faut que tous puissent rajouter des noms et seulement les PFO et
--    coordinateurs retirer. Les medicaux doivent cocher et les sociaux aussi.
--    Une fois que les 2 sont coches, c'est que la personne a ete vue en
--    entretien. Pareil pour les entretiens mi-parcours."
--
-- UNE LIGNE PAR ENTRANT : nom, chambre, date d'arrivee, et QUATRE CASES --
--   arrivee : sociale, medicale ;  mi-parcours : sociale, medicale.
-- Chaque case garde QUAND et PAR QUI elle a ete cochee : c'est le "qui".
--
-- ==== LA REGLE DU GROUPE D EST ICI, DANS LA BASE, ET PAS DANS L'ECRAN ====
-- Le 07/09 on a trouve que le masquage par groupe de l'ecran ne marche qu'en
-- apercu. Pour des NOMS de personnes hebergees, cacher un bouton ne suffit pas :
-- c'est la base qui refuse de donner la liste.
-- Et c'est une LISTE D'AUTORISES, pas d'interdits : un metier cree demain n'a
-- pas acces tant qu'il n'est pas ajoute ci-dessous. Un oubli ferme, il n'ouvre pas.
--
-- ==== CE QUE LA TABLE NE GARDE PAS ====
-- Ni date de naissance, ni situation, ni motif. Le dossier, c'est KAIROS.
--
-- (Pas d'accents dans ce fichier : l'editeur SQL les abime. Les metiers accentues
--  sont compares sans accents, via equipe_propre.)
-- ===========================================================================

-- Le nom d'un metier, en minuscules et sans accents : "Medecin" et "Medecin" accentue, c est pareil.
create or replace function public.equipe_propre(e text)
returns text language sql immutable as $$
  select translate(lower(coalesce(e, '')),
                   U&'\00e9\00e8\00ea\00eb\00e0\00e2\00e7\00c9\00c8',
                   'eeeeaacee');
$$;

-- Groupes A, B, C : l'administration, la coordination, et ceux qui travaillent
-- aupres des personnes. Les anciens noms de metier sont gardes (TS, Infi...) :
-- une ligne restee sur un vieux nom ne doit pas perdre l'acces en silence.
create or replace function public.peut_voir_entrants()
returns boolean language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.allowed_emails a
     where lower(a.email) = lower(auth.jwt() ->> 'email')
       and coalesce(a.actif, true)
       and ( coalesce(a.admin, false)
          or public.equipe_propre(a.equipe) in (
               'admin', 'coordination', 'coordi',
               'travailleur social', 'ts',
               'medecin', 'medical',
               'infirmier', 'infi',
               'aide-soignant', 'aide-soignante',
               'educateur', 'educ',
               'psychologue', 'psy',
               'travaux / maintenance', 'logistique') ) );
$$;

-- Retirer : les PFO, la coordination, l'administration -- et seulement s'ils
-- voient deja la liste (un PFO du groupe D, s'il en existe, n'y a pas acces).
create or replace function public.peut_retirer_entrants()
returns boolean language sql stable security definer set search_path = public as $$
  select public.peut_voir_entrants() and exists (
    select 1 from public.allowed_emails a
     where lower(a.email) = lower(auth.jwt() ->> 'email')
       and coalesce(a.actif, true)
       and ( coalesce(a.admin, false) or coalesce(a.pfo, false)
          or public.equipe_propre(a.equipe) in ('admin', 'coordination', 'coordi') ) );
$$;
-- (18/09/2026, verifie par simulation : le compte dont le METIER est "Admin" voyait la
--  liste mais ne pouvait pas retirer -- il n'a pas la case admin cochee. Le groupe A a
--  toujours tout : son metier suffit.)

grant execute on function public.equipe_propre(text) to authenticated;
grant execute on function public.peut_voir_entrants() to authenticated;
grant execute on function public.peut_retirer_entrants() to authenticated;

create table if not exists public.entrants (
  id              bigint generated by default as identity primary key,
  nom             text        not null check (char_length(nom) between 1 and 80),
  chambre         text                 check (chambre is null or char_length(chambre) <= 12),
  arrive_le       date        not null default (now() at time zone 'Europe/Brussels')::date,
  -- l'entretien d'arrivee
  acc_social_le   timestamptz, acc_social_par  text,
  acc_medical_le  timestamptz, acc_medical_par text,
  -- l'entretien de mi-parcours
  mi_social_le    timestamptz, mi_social_par   text,
  mi_medical_le   timestamptz, mi_medical_par  text,
  ajoute_par      text,
  uid             uuid        not null default auth.uid(),
  cree_le         timestamptz not null default now()
);

alter table public.entrants enable row level security;

drop policy if exists ent_lecture on public.entrants;
create policy ent_lecture on public.entrants for select to authenticated
  using (public.peut_voir_entrants());

-- Tout le monde (A, B, C) ajoute un nom.
drop policy if exists ent_ajout on public.entrants;
create policy ent_ajout on public.entrants for insert to authenticated
  with check (public.peut_voir_entrants() and uid = auth.uid());

-- Tout le monde (A, B, C) coche : le social coche le social, le medical le medical.
drop policy if exists ent_cocher on public.entrants;
create policy ent_cocher on public.entrants for update to authenticated
  using (public.peut_voir_entrants()) with check (public.peut_voir_entrants());

-- Retirer : PFO, coordination, administration.
drop policy if exists ent_retirer on public.entrants;
create policy ent_retirer on public.entrants for delete to authenticated
  using (public.peut_retirer_entrants());

-- La cle de la porte (les policies ne suffisent pas, voir 08/08/2026).
grant select, insert, update, delete on public.entrants to authenticated;

-- -- PASSE DANS SUPABASE LE 18/09/2026 -- "Success. No rows returned".
-- Verifie compte par compte (fonction temporaire pg_temp.test_ent, rien de garde) :
--   Polyvalent : ne voit pas, ne retire pas.   Compte sans metier : idem.
--   Aide-soignant, Educateur, Infirmier, Logistique, Medecin, Psychologue,
--   Travailleur social : voient, ne retirent pas.
--   Coordination, Travailleur social PFO, Admin : voient ET retirent.
