-- ═══ EXÉCUTÉ le 06/10/2026 par Claude (éditeur SQL) : table + déclencheur créés. ═══
-- ═══════════════════════════════════════════════════════════════════════════
-- ENTRANTS — la corbeille, pour savoir qui est DÉJÀ PASSÉ   (06/10/2026)
--
-- Mag : « pour Monsieur Irfan, qui est déjà passé, il faut que tu dises : c'est passé
-- dans la base de données, ça a déjà été validé, et ça a été passé à la corbeille. »
-- « Retirer » effaçait la ligne sans trace : un mail d'entrants recollé plus tard la
-- faisait revenir comme « nouvelle ». Un déclencheur garde une copie de chaque ligne
-- retirée (nom, LAM/MÉD, jour d'arrivée, quand, qui). Il tourne dans la base : aucun
-- oubli possible côté app.
-- ⚠ ON NE GARDE PAS LONGTEMPS : 15 jours (Mag : « tu peux t'en souvenir sur l'espace de 15 jours »), puis la copie s'efface toute seule.
-- Lecture : ceux qui voient les entrants. Écriture : le déclencheur seul.
-- Re-jouable.
-- ═══════════════════════════════════════════════════════════════════════════
create table if not exists public.entrants_corbeille (
  id          bigint generated by default as identity primary key,
  nom         text not null,
  lam         boolean,
  arrive_le   date,
  retire_le   timestamptz not null default now(),
  retire_par  text
);
alter table public.entrants_corbeille enable row level security;
drop policy if exists entc_lecture on public.entrants_corbeille;
create policy entc_lecture on public.entrants_corbeille for select to authenticated
  using (public.peut_voir_entrants());
grant select on public.entrants_corbeille to authenticated;

create or replace function public.entrants_vers_corbeille()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.entrants_corbeille (nom, lam, arrive_le, retire_par)
  values (old.nom, old.lam, old.arrive_le, auth.jwt() ->> 'email');
  delete from public.entrants_corbeille where retire_le < now() - interval '15 days';
  return old;
end $$;
drop trigger if exists entrants_corbeille_t on public.entrants;
create trigger entrants_corbeille_t after delete on public.entrants
  for each row execute function public.entrants_vers_corbeille();

select count(*) as lignes_corbeille from public.entrants_corbeille;
