-- ═══ LE BACKUP DES NOTES (Mag, 08/10/2026) ═══
-- « Parfois, dans Kairos, il y a des notes qui se perdent. Mais comme j'ai déjà effacé
--   dans Cousin, j'ai complètement perdu ma note. »
-- La poubelle de Ma liste et de la page Notes demande : « Backup 7 jours » ou
-- « Effacer pour de bon ». Le backup garde la ligne ENTIÈRE (`donnees`) pour pouvoir la
-- remettre telle quelle. Privé : chacun ne voit, n'ajoute et ne retire que les siennes.
-- Les lignes de plus de 7 jours sont retirées par l'app au chargement (et ignorées avant).
create table if not exists public.notes_backup (
  id       bigint generated by default as identity primary key,
  uid      uuid        not null default auth.uid(),
  origine  text        not null default 'liste',   -- 'liste' (Ma liste perso) | 'notes' (page Notes)
  texte    text        not null,
  donnees  jsonb,
  cree_le  timestamptz not null default now()
);
create index if not exists notes_backup_uid_idx on public.notes_backup (uid, cree_le);
alter table public.notes_backup enable row level security;
drop policy if exists nb_lecture on public.notes_backup;
create policy nb_lecture on public.notes_backup for select to authenticated using (uid = auth.uid());
drop policy if exists nb_ecriture on public.notes_backup;
create policy nb_ecriture on public.notes_backup for insert to authenticated with check (uid = auth.uid());
drop policy if exists nb_suppr on public.notes_backup;
create policy nb_suppr on public.notes_backup for delete to authenticated using (uid = auth.uid());
grant select, insert, delete on public.notes_backup to authenticated;
