-- ===========================================================================
-- COUSIN -- Les numeros de la maraude (26/09/2026)
-- Mag : "rajoute ces contacts [...] tout le monde ne peut pas avoir acces, donc
-- certainement pas le groupe D". Puis : un bouton dans le Centre, groupes A, B, C.
--
-- ==== POURQUOI UNE TABLE ET PAS LE CODE ====
-- Ce sont des portables de collegues. Le code de l'app est PUBLIC (GitHub) : cache
-- a l'ecran, un numero ecrit dans index.html se lirait quand meme. Ici, c'est la
-- base qui refuse de l'envoyer a un compte du groupe D.
--
-- ==== QUI LIT ====
-- peut_voir_entrants() (sql/entrants.sql) : administration, coordination, et les
-- metiers aupres des personnes -- exactement A, B, C. Une liste d'autorises : un
-- metier cree demain n'y a pas acces tant qu'on ne l'ajoute pas.
-- Personne n'ecrit depuis l'app : on corrige ici, dans l'editeur SQL.
--
-- (Pas d'accents dans ce fichier : l'editeur SQL les abime -- les noms accentues
--  sont ecrits en U&'...'.)
-- ===========================================================================

create table if not exists public.numeros_internes (
  id      bigint generated by default as identity primary key,
  bloc    text not null,          -- le titre sous lequel la ligne se range
  ordre   int  not null default 0,
  nom     text not null,
  role    text,
  tel     text not null,
  note    text                    -- ce qui change ce qu'on fait (jour off, doute)
);

alter table public.numeros_internes enable row level security;
drop policy if exists numeros_internes_lire on public.numeros_internes;
create policy numeros_internes_lire on public.numeros_internes
  for select to authenticated using (public.peut_voir_entrants());
-- Sans grant, "permission denied" (voir la memoire du grant des nouvelles tables).
grant select on public.numeros_internes to authenticated;

-- La feuille punaisee "Numeros maraude", photographiee par Mag le 26/09/2026.
-- On repart de zero a chaque passage : le fichier EST la liste.
delete from public.numeros_internes where bloc like 'Maraude%' or bloc = 'Gsm de service';
insert into public.numeros_internes (bloc, ordre, nom, role, tel, note) values
  ('Gsm de service', 1, 'Maraude 1', null, '0490 30 00 82', null),
  ('Gsm de service', 2, 'Maraude 2', null, '0490 30 00 83', null),
  ('Maraude - responsables', 1, 'Vincent', 'responsable', '0498 90 57 27', null),
  ('Maraude - responsables', 2, U&'Rafa\00ebl', 'coordi', '0491 61 35 51', 'Ne travaille pas le vendredi'),
  ('Maraude jour', 1, 'Gaby', 'TS', '0492 90 67 53', null),
  ('Maraude jour', 2, 'Amelia', 'TS', '0499 60 31 37', null),
  ('Maraude jour', 3, U&'Dieudonn\00e9', 'TS', '0494 17 64 71', null),
  ('Maraude jour', 4, 'Sonia', 'psy', '0490 30 00 54', null),
  ('Maraude jour', 5, 'Robin', 'psy', '0494 17 64 63', null),
  -- La feuille donne le MEME numero a Christelle et a Thomas : un des deux est faux.
  -- On ne choisit pas -- les deux lignes le disent, jusqu'a ce que Mag tranche.
  ('Maraude jour', 6, 'Christelle', 'infi', '0499 68 93 72', U&'M\00eame num\00e9ro que Thomas sur la feuille : \00e0 v\00e9rifier'),
  ('Maraude jour', 7, 'Sabrine', 'infi', '0498 64 11 47', null),
  ('Maraude jour', 8, 'Thomas', 'AS', '0499 68 93 72', U&'M\00eame num\00e9ro que Christelle sur la feuille : \00e0 v\00e9rifier'),
  ('Maraude jour', 9, 'Aline', 'AS', '0499 05 86 22', null);
