-- ═══ LES RÉPONSES SOUS UNE PASSATION DU SERVICE SOCIAL (Mag, 07/10/2026) ═══
-- « Pourquoi il y en a deux, tout doit être ensemble » : la liste à deux avec Afaf et la
-- passation du service social deviennent UNE carte. On y répond sous la ligne.
-- Lecture : tout le monde connecté (comme `passations`). Écrire / retirer : sa réponse.
create table if not exists public.passation_reponses (
  id             bigint generated by default as identity primary key,
  passation_id   bigint      not null references public.passations(id) on delete cascade,
  texte          text        not null,
  par            text,
  uid            uuid        not null default auth.uid(),
  cree_le        timestamptz not null default now()
);
create index if not exists passation_reponses_idx on public.passation_reponses (passation_id);
alter table public.passation_reponses enable row level security;
drop policy if exists pr_lecture on public.passation_reponses;
create policy pr_lecture on public.passation_reponses for select to authenticated using (true);
drop policy if exists pr_ecriture on public.passation_reponses;
create policy pr_ecriture on public.passation_reponses for insert to authenticated with check (uid = auth.uid());
drop policy if exists pr_suppr on public.passation_reponses;
create policy pr_suppr on public.passation_reponses for delete to authenticated using (uid = auth.uid());
grant select, insert, delete on public.passation_reponses to authenticated;
