-- ═══════════════════════════════════════════════════════════════════════════
-- LA PASSATION — demandée par Mag le 08/08/2026
--
--   « Dans les notes, la liste de notes pour les personnels, pour les PFO de
--    journée, il devrait y avoir un truc, un bouton où on pourrait dire à qui on
--    doit faire la passation. À l'équipe de nuit, c'est très important. Dans
--    l'équipe de nuit, parfois c'est juste une passation, parfois c'est des
--    réveils. Donc c'est bien de pouvoir affiner ça. »
--
-- DEUX CHOSES À AFFINER, ET C'EST TOUT LE FICHIER :
--   `pour`  → À QUI. La clé d'une liste de rôle : pfo-nuit, polyvalent-nuit,
--             médical, pfo-jour… les mêmes que les check-lists, pour que ça tombe
--             dans la liste des bonnes personnes sans rien réorganiser.
--   `genre` → QUOI. « passation » (une info à transmettre) ou « réveil » (aller
--             réveiller quelqu'un). Un réveil porte une HEURE et une CHAMBRE ;
--             une passation, non. C'est la distinction qu'elle demande.
--
-- ⚠ POURQUOI L'HEURE COMPTE POUR UN RÉVEIL. Une passation se lit en arrivant ;
-- un réveil se fait à 5 h 30 et pas à 7 h. Les réveils sont donc rangés par heure,
-- avant le reste : c'est un horaire, pas une liste de courses.
--
-- ⚠ AUCUN NOM. Numéro de chambre et initiales, comme sur les chambres — la règle
-- de COUSIN vaut ici aussi. Et jamais un motif médical : le réveil dit d'aller
-- réveiller la chambre 312 à 5 h 30, pas pourquoi.
--
-- ⚠ `jour` EST LE JOUR DE LA PASSATION, avec l'heure de Bruxelles pour défaut. Sans
-- lui, la liste de la nuit s'allongerait indéfiniment et l'équipe qui arrive
-- relirait les nuits d'avant.
--
-- ═══ QUI PEUT COCHER ═══
-- Tout le monde lit, tout le monde coche. C'est volontaire, et c'est même l'objet :
-- une passation adressée à l'équipe de nuit doit pouvoir être cochée PAR l'équipe de
-- nuit — pas par celle qui l'a écrite et qui est rentrée dormir. Supprimer, par
-- contre, reste à l'auteur : on peut faire le travail de quelqu'un, pas effacer sa
-- consigne.
-- ═══════════════════════════════════════════════════════════════════════════

create table if not exists public.passations (
  id       bigint generated by default as identity primary key,
  texte    text        not null,
  pour     text        not null,                 -- clé de rôle : 'pfo-nuit', 'médical'…
  genre    text        not null default 'passation',   -- 'passation' | 'reveil'
  jour     date        not null default (now() at time zone 'Europe/Brussels')::date,
  heure    text,                                -- pour un réveil : « 05:30 »
  chambre  text,                                -- pour un réveil : « 312 »
  fait_le  timestamptz,
  fait_par text,
  par      text,                                -- le prénom de qui a écrit
  uid      uuid        not null default auth.uid(),
  cree_le  timestamptz not null default now()
);

create index if not exists passations_jour_idx on public.passations (jour, pour);

alter table public.passations enable row level security;

drop policy if exists pass_lecture on public.passations;
create policy pass_lecture on public.passations for select to authenticated using (true);

drop policy if exists pass_ecriture on public.passations;
create policy pass_ecriture on public.passations for insert to authenticated
  with check (uid = auth.uid());

-- Celui à qui la passation est adressée doit pouvoir la cocher : c'est tout l'objet.
drop policy if exists pass_maj on public.passations;
create policy pass_maj on public.passations for update to authenticated
  using (true) with check (true);

drop policy if exists pass_suppr on public.passations;
create policy pass_suppr on public.passations for delete to authenticated
  using (uid = auth.uid());

-- ── PASSÉ DANS SUPABASE LE 08/08/2026 ────────────────────────────────────────
-- « Success. No rows returned ».
