-- ═══════════════════════════════════════════════════════════════════════════
-- LES ACTIVITÉS AU CENTRE — LE CARNET DES PROPOSITIONS (Mag, 08/08/2026)
--
--   « Pour les activités au centre, on devrait pouvoir noter les propositions et
--    les demandes des hébergés, en plus des idées des éducs et des suggestions de
--    l'équipe. »
--
-- `source` — D'OÙ ÇA VIENT, et c'est le cœur de sa demande :
--   'heberge' → quelqu'un du centre l'a demandé
--   'educ'    → une idée d'éducateur
--   'equipe'  → une suggestion de l'équipe
-- La même phrase ne vaut pas la même chose selon qui la dit. « On pourrait faire
-- un atelier couture » venant de l'équipe, c'est une idée ; venant de trois
-- hébergés, c'est une demande à laquelle le centre ne répond pas.
--
-- `demandee` — COMBIEN DE FOIS ça a été demandé. Trois personnes qui réclament la
-- même chose, ce n'est plus une idée, c'est un besoin — et c'est ce chiffre-là qui
-- sert à décider quoi lancer en premier.
--
-- ⚠ CE N'EST PAS UN PROGRAMME, ET C'EST VOULU. Un carnet de propositions
-- n'engage personne à animer quoi que ce soit. C'est exactement ce qui avait fait
-- écarter l'agenda des activités le 30/07/2026 : « c'est un peu trop de pression
-- pour l'instant pour les travailleurs éducs ». Noter une demande ne promet rien ;
-- afficher un programme, si. Ne pas transformer ce carnet en calendrier sans elle.
--
-- ⚠ AUCUN NOM D'HÉBERGÉ, pas même des initiales. On note QUE quelqu'un l'a
-- demandé, jamais qui : une envie d'atelier n'a pas à être attachée à une personne
-- dans un outil que toute l'équipe lit.
--
-- ═══ QUI PEUT QUOI ═══
-- Tout le monde écrit, tout le monde met « +1 » et marque qu'on l'a essayée : ceux
-- qui recueillent les demandes sont ceux qui sont au contact, pas l'administration.
-- Supprimer reste à l'auteur.
-- ═══════════════════════════════════════════════════════════════════════════

create table if not exists public.propositions (
  id       bigint generated by default as identity primary key,
  texte    text        not null,
  source   text        not null default 'equipe',   -- heberge | educ | equipe
  note     text,                                   -- matériel, durée, nombre de gens
  demandee smallint    not null default 1,
  etat     text        not null default 'idee',     -- idee | essayer | faite
  fait_le  timestamptz,
  fait_par text,
  par      text,
  uid      uuid        not null default auth.uid(),
  cree_le  timestamptz not null default now()
);

create index if not exists propositions_etat_idx on public.propositions (etat, source);

alter table public.propositions enable row level security;

drop policy if exists prop_lecture on public.propositions;
create policy prop_lecture on public.propositions for select to authenticated using (true);

drop policy if exists prop_ecriture on public.propositions;
create policy prop_ecriture on public.propositions for insert to authenticated
  with check (uid = auth.uid());

-- Tout le monde peut ajouter une demande de plus et marquer qu'on l'a essayée.
drop policy if exists prop_maj on public.propositions;
create policy prop_maj on public.propositions for update to authenticated
  using (true) with check (true);

drop policy if exists prop_suppr on public.propositions;
create policy prop_suppr on public.propositions for delete to authenticated
  using (uid = auth.uid());

-- ── PASSÉ DANS SUPABASE LE 08/08/2026 ────────────────────────────────────────
-- « Success. No rows returned ».
