-- ═══ LE PROTOCOLE PUNAISES DU JEUDI (Mag, 08/10/2026) ═══
-- Chaque jeudi, Rentokil traite 4-5 chambres (produit 12 h → 17 h, la personne rentre à 17 h).
-- Une ligne = une chambre pour un jeudi. Quatre étapes, chacune signée et datée :
--   A prévenu · B sacs faits (par la personne, ou avec l'aide-soignant·e — JAMAIS sans elle)
--   C descendu en protocole · D sacs rendus (vendredi matin) = terminé.
-- Pas prévenu à midi le jeudi = abandonné : ça se CALCULE (jour + 12 h), rien n'est stocké.
-- Tout le monde lit, ajoute, coche, en signant (comme le tour des chambres). Numéro de chambre
-- et initiales seulement, jamais de nom.
create table if not exists public.protocole_punaises (
  id            bigint generated by default as identity primary key,
  jour          date        not null,            -- le jeudi du traitement
  numero        text        not null,
  initiales     text,
  prevenu_le    timestamptz,
  prevenu_par   text,
  sacs_le       timestamptz,
  sacs_par      text,
  sacs_qui      text,                            -- 'personne' | 'aide-soignant'
  descendu_le   timestamptz,
  descendu_par  text,
  rendu_le      timestamptz,
  rendu_par     text,
  journal       jsonb       not null default '[]'::jsonb,   -- {le, par, txt} : « pas vu à 21 h »…
  cree_le       timestamptz not null default now(),
  cree_par      text
);
create index if not exists protocole_punaises_jour_idx on public.protocole_punaises (jour);
alter table public.protocole_punaises enable row level security;
drop policy if exists pp_lecture on public.protocole_punaises;
create policy pp_lecture on public.protocole_punaises for select to authenticated using (true);
drop policy if exists pp_ecriture on public.protocole_punaises;
create policy pp_ecriture on public.protocole_punaises for insert to authenticated with check (true);
drop policy if exists pp_maj on public.protocole_punaises;
create policy pp_maj on public.protocole_punaises for update to authenticated using (true) with check (true);
drop policy if exists pp_suppr on public.protocole_punaises;
create policy pp_suppr on public.protocole_punaises for delete to authenticated using (true);
grant select, insert, update, delete on public.protocole_punaises to authenticated;
