-- ═══ LES RENDEZ-VOUS ET ACCOMPAGNEMENTS (Mag, 08/10/2026) ═══
-- Un agenda commun à l'équipe : rendez-vous médicaux, sociaux, administratifs, et qui
-- accompagne. Tout le monde lit (polyvalents compris, nom en entier : tranché le 08/10).
-- Tout le monde écrit SAUF les polyvalents (« tous sauf les polyvalents »).
-- Les rendez-vous passés restent 14 jours (« un backup de 2 semaines en arrière »), puis
-- l'app les retire.
-- Les mails de rappel viendront plus tard (compte d'envoi à créer) : `accomp_email` sert à
-- savoir à qui écrire ; un nom écrit à la main n'a pas d'adresse et ne reçoit rien.
create table if not exists public.rendez_vous (
  id            bigint generated by default as identity primary key,
  jour          date        not null,
  heure         text,                       -- « 09:30 »
  nom           text        not null,
  chambre       text,
  genre         text        not null default 'medical',   -- medical | social | administratif | autre
  lieu          text,
  adresse       text,
  accompagne    boolean     not null default false,
  accomp_email  text,                       -- le collègue, s'il a un compte
  accomp_nom    text,                       -- son prénom, ou un nom écrit à la main ; vide = « à trouver »
  note          text,
  cree_par      text,
  cree_email    text        default lower(auth.jwt() ->> 'email'),
  cree_le       timestamptz not null default now(),
  modifie_par   text,
  modifie_le    timestamptz
);
create index if not exists rendez_vous_jour_idx on public.rendez_vous (jour);

create or replace function public.peut_ecrire_rdv()
returns boolean language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.allowed_emails a
     where lower(a.email) = lower(auth.jwt() ->> 'email')
       and coalesce(a.actif, true)
       and ( coalesce(a.admin, false)
          or public.equipe_propre(a.equipe) not like 'polyvalent%' ) );
$$;
revoke all on function public.peut_ecrire_rdv() from public;
grant execute on function public.peut_ecrire_rdv() to authenticated;

-- Les prénoms de l'équipe, pour choisir qui accompagne.
-- ⚠ 09/10/2026 : « tu ne marques jamais Magali, tu mets Mag » : le PSEUDO du profil passe
-- avant le prénom Google.
-- ⚠ 09/10/2026 : « ici, il ne doit absolument pas y avoir les polyvalents, ni les
-- coordinateurs ». Et un même compte Google en double (tes deux adresses) ne fait
-- qu'un prénom : on garde l'adresse samusocial.
create or replace function public.equipe_prenoms()
returns table(email text, prenom text)
language plpgsql stable security definer set search_path = public as $$
begin
  if not exists (select 1 from public.allowed_emails a
                  where lower(a.email) = lower(auth.jwt() ->> 'email') and coalesce(a.actif, true))
  then return; end if;
  return query
    select x.email, x.prenom from (
      select distinct on (lower(coalesce(nullif(u.raw_user_meta_data ->> 'full_name', ''), a.email)))
             lower(a.email)::text as email,
             coalesce(
               nullif(trim(ps.valeur #>> '{}'), ''),
               nullif(split_part(coalesce(u.raw_user_meta_data ->> 'full_name',
                                          u.raw_user_meta_data ->> 'name', ''), ' ', 1), ''),
               initcap(split_part(split_part(a.email, '@', 1), '.', 1))
             )::text as prenom
        from public.allowed_emails a
        left join auth.users u on lower(u.email) = lower(a.email)
        left join public.reglages_perso ps on ps.user_id = u.id and ps.cle = 'pseudo'
       where coalesce(a.actif, true)
         and public.equipe_propre(a.equipe) not like 'polyvalent%'
         and public.equipe_propre(a.equipe) not in ('coordi', 'coordination')
       order by lower(coalesce(nullif(u.raw_user_meta_data ->> 'full_name', ''), a.email)),
                (lower(a.email) like '%@samusocial.be') desc
    ) x
    order by 2;
end $$;
revoke all on function public.equipe_prenoms() from public;
grant execute on function public.equipe_prenoms() to authenticated;

alter table public.rendez_vous enable row level security;
drop policy if exists rdv_lecture on public.rendez_vous;
create policy rdv_lecture on public.rendez_vous for select to authenticated using (true);
drop policy if exists rdv_ecriture on public.rendez_vous;
create policy rdv_ecriture on public.rendez_vous for insert to authenticated with check (public.peut_ecrire_rdv());
drop policy if exists rdv_maj on public.rendez_vous;
create policy rdv_maj on public.rendez_vous for update to authenticated using (public.peut_ecrire_rdv()) with check (public.peut_ecrire_rdv());
drop policy if exists rdv_suppr on public.rendez_vous;
create policy rdv_suppr on public.rendez_vous for delete to authenticated using (public.peut_ecrire_rdv());
grant select, insert, update, delete on public.rendez_vous to authenticated;
