-- ═══════════════════════════════════════════════════════════════════════════
-- LE TOUR DES CHAMBRES — les bacs en trop
-- Demandé par Mag le 08/08/2026 :
--   « Pour le tour des chambres, on doit faire le tour et vérifier s'il y a des
--    sacs en trop. Normalement on a droit à 3 bacs. Donc il faudrait pouvoir
--    noter combien de bacs il y a en trop. Je mettrais les initiales de la
--    personne aussi. Et le jour où on a prévenu — un jour, il faut le jeter. »
--
-- CE QUE ÇA N'EST PAS : ce n'est pas la table `chambres`, qui suit le PARCOURS
-- D'UNE CHAMBRE QUI SE LIBÈRE (désencoder, vider, nettoyer, libérer). Ici la
-- chambre est OCCUPÉE : on constate un excédent, on prévient, et on laisse un
-- délai avant de jeter. Deux histoires différentes, deux tables.
--
-- ⚠ AUCUN NOM. Des INITIALES seulement, comme sur les chambres — c'est la règle
-- de COUSIN et elle vaut ici : ce registre dit qu'on a prévenu quelqu'un, il ne
-- doit pas dire qui c'est.
--
-- ═══ POURQUOI CE REGISTRE EXISTE (Mag, 08/08/2026) ═══
-- « Le but de ça, c'est de faire une PASSATION ENTRE LES ÉQUIPES. »
--
-- Ce n'est donc pas un pense-bête personnel : c'est un relais. Les ÉDUCATEURS
-- font le tour et notent — ils travaillent en 4-4 (quatre jours de travail,
-- quatre jours de repos). Les PFO, qui tournent en 7-7, SUPERVISENT et voient
-- passer les deux équipes d'éducateurs.
--
-- LE DÉLAI EST DE TROIS JOURS après l'avertissement : « tant qu'ils fassent le
-- tri, qu'ils donnent ça à des gens pour ne pas jeter, ou alors qu'ils les
-- jettent ». Trois jours, ce n'est pas un chiffre rond posé au hasard : il tombe
-- DANS le cycle de 4 jours de l'équipe qui a prévenu. Celle qui avertit est donc
-- encore là quand le délai expire — elle n'abandonne pas la décision à la
-- suivante, et personne n'hérite d'un « à jeter » sans savoir ce qui a été dit.
--
-- ⚠ CE QUI SE DÉDUIT, ET CE QUI SE SAISIT. `prevenu_le` est saisi ; l'échéance
-- (prevenu_le + 3 jours) se CALCULE à l'affichage. Une colonne « à jeter le »
-- figerait la règle dans chaque ligne : le jour où le délai changerait, les
-- anciennes lignes garderaient l'ancien. La règle vit dans le code, une seule
-- fois, et toutes les lignes la suivent.
-- ═══════════════════════════════════════════════════════════════════════════

create table if not exists public.tour_bacs (
  id          bigint generated by default as identity primary key,
  numero      text        not null,              -- le numéro de chambre
  initiales   text,                              -- 14 caractères max côté app, jamais le nom complet
  bacs        smallint    not null default 0,    -- COMBIEN EN TROP, pas le total. 3 sont dus.
  prevenu_le  date,                              -- le jour où on a prévenu la personne
  prevenu_par text,                              -- le prénom de qui a prévenu (nomAffiche)
  regle_le    timestamptz,                       -- quand c'est rentré dans l'ordre : la ligne se ferme
  regle_par   text,
  note        text,                              -- « deux bacs sous le lit », si besoin
  cree_le     timestamptz not null default now(),
  cree_par    text
);

-- On lit toujours « ce qui n'est pas réglé, du plus ancien au plus récent » :
-- c'est le plus ancien avertissement qui devient urgent en premier.
create index if not exists tour_bacs_ouvert_idx
  on public.tour_bacs (regle_le, prevenu_le);

-- ── QUI PEUT QUOI ────────────────────────────────────────────────────────────
-- Même règle que la table `chambres` : toute l'équipe connectée lit et écrit.
-- Ce sont les agents d'entretien et les polyvalents qui font le geste ; la
-- sécurité, ce n'est pas d'empêcher, c'est de savoir qui a fait quoi.
alter table public.tour_bacs enable row level security;

drop policy if exists tour_bacs_lecture on public.tour_bacs;
create policy tour_bacs_lecture on public.tour_bacs
  for select to authenticated using (true);

drop policy if exists tour_bacs_ecriture on public.tour_bacs;
create policy tour_bacs_ecriture on public.tour_bacs
  for insert to authenticated with check (true);

drop policy if exists tour_bacs_maj on public.tour_bacs;
create policy tour_bacs_maj on public.tour_bacs
  for update to authenticated using (true) with check (true);

drop policy if exists tour_bacs_suppr on public.tour_bacs;
create policy tour_bacs_suppr on public.tour_bacs
  for delete to authenticated using (true);

-- ── À VÉRIFIER APRÈS AVOIR LANCÉ CECI ────────────────────────────────────────
-- select * from public.tour_bacs;            -- doit répondre « 0 lignes », pas une erreur
