-- ═══ EXÉCUTÉ le 06/10/2026 par Claude (via l app connectée, compte admin) : 29 lignes insérées, vérifiées. ═══
-- Programme d'OCTOBRE 2026 de WAKA UP, encodé d'après leur calendrier
-- (image envoyée par Mag le 05/10/2026). Texte en base64 : le presse-papier vers
-- l'éditeur SQL abîme les accents. pour_qui = 'femmes' DÈS l'encodage (voir waka-femmes.sql).
--
-- ATTENTION AUX LIEUX. Le calendrier ne dit pas où se passent : le vernissage (2),
-- le foot en salle (mardis), les ateliers Karibu (14), le festival (25), le tricot
-- @ Crazy (29) et l'escalade (30). Ces lignes portent « Lieu à confirmer » plutôt
-- qu'une adresse inventée.
-- Les lundis portent le lotus : « moment bien-être sur rendez-vous, réservation par
-- message » — encodé comme une ligne à part, sans heure.
delete from public.activites where asso = convert_from(decode('V0FLQSBVUA==','base64'),'UTF8') and jour >= '2026-10-01' and jour <= '2026-10-31';
insert into public.activites (asso, titre, jour, debut, fin, lieu, adresse, gratuit, inscription, ajoute_par, pour_qui) values
(convert_from(decode('V0FLQSBVUA==','base64'),'UTF8'), convert_from(decode('SW5zdGFudCB6ZW4=','base64'),'UTF8'), '2026-10-01', convert_from(decode('MTBo','base64'),'UTF8'), convert_from(decode('MTJo','base64'),'UTF8'), convert_from(decode('Q2hleiBXQUtBIFVQ','base64'),'UTF8'), convert_from(decode('QXZlbnVlIGRlIEpldHRlIDIyNSwgMTA5MCBKZXR0ZSAocG9ydGFpbCB2ZXJ0KQ==','base64'),'UTF8'), true, convert_from(decode('SW5zY3JpcHRpb24gOiAwNDc0IDg1IDc4IDI1IMK3IGluZm9Ad2FrYS11cC5iZQ==','base64'),'UTF8'), convert_from(decode('Q2xhdWRlLCBkJ2FwcsOocyBsZXVyIGNhbGVuZHJpZXIgZCdvY3RvYnJlIDIwMjY=','base64'),'UTF8'), 'femmes'),
(convert_from(decode('V0FLQSBVUA==','base64'),'UTF8'), convert_from(decode('RXhwb3NpdGlvbiBwaG90byBjb2xsZWN0aXZlIOKAlCB2ZXJuaXNzYWdl','base64'),'UTF8'), '2026-10-02', null, null, convert_from(decode('TGlldSDDoCBjb25maXJtZXIg4oCUIGFwcGVsZXIgV0FLQSBVUA==','base64'),'UTF8'), null, true, convert_from(decode('SW5zY3JpcHRpb24gOiAwNDc0IDg1IDc4IDI1IMK3IGluZm9Ad2FrYS11cC5iZQ==','base64'),'UTF8'), convert_from(decode('Q2xhdWRlLCBkJ2FwcsOocyBsZXVyIGNhbGVuZHJpZXIgZCdvY3RvYnJlIDIwMjY=','base64'),'UTF8'), 'femmes'),
(convert_from(decode('V0FLQSBVUA==','base64'),'UTF8'), convert_from(decode('TW9tZW50IGJpZW4tw6p0cmUg4oCUIHN1ciByZW5kZXotdm91cw==','base64'),'UTF8'), '2026-10-05', null, null, convert_from(decode('Q2hleiBXQUtBIFVQ','base64'),'UTF8'), convert_from(decode('QXZlbnVlIGRlIEpldHRlIDIyNSwgMTA5MCBKZXR0ZSAocG9ydGFpbCB2ZXJ0KQ==','base64'),'UTF8'), true, convert_from(decode('UsOpc2VydmF0aW9uIHBhciBtZXNzYWdlIDogMDQ3NCA4NSA3OCAyNQ==','base64'),'UTF8'), convert_from(decode('Q2xhdWRlLCBkJ2FwcsOocyBsZXVyIGNhbGVuZHJpZXIgZCdvY3RvYnJlIDIwMjY=','base64'),'UTF8'), 'femmes'),
(convert_from(decode('V0FLQSBVUA==','base64'),'UTF8'), convert_from(decode('Qm94ZQ==','base64'),'UTF8'), '2026-10-05', convert_from(decode('MTBo','base64'),'UTF8'), convert_from(decode('MTFoMzA=','base64'),'UTF8'), convert_from(decode('Q2hleiBXQUtBIFVQ','base64'),'UTF8'), convert_from(decode('QXZlbnVlIGRlIEpldHRlIDIyNSwgMTA5MCBKZXR0ZSAocG9ydGFpbCB2ZXJ0KQ==','base64'),'UTF8'), true, convert_from(decode('SW5zY3JpcHRpb24gOiAwNDc0IDg1IDc4IDI1IMK3IGluZm9Ad2FrYS11cC5iZQ==','base64'),'UTF8'), convert_from(decode('Q2xhdWRlLCBkJ2FwcsOocyBsZXVyIGNhbGVuZHJpZXIgZCdvY3RvYnJlIDIwMjY=','base64'),'UTF8'), 'femmes'),
(convert_from(decode('V0FLQSBVUA==','base64'),'UTF8'), convert_from(decode('VHJpY290','base64'),'UTF8'), '2026-10-05', convert_from(decode('MTNoMzA=','base64'),'UTF8'), convert_from(decode('MTZo','base64'),'UTF8'), convert_from(decode('Q2hleiBXQUtBIFVQ','base64'),'UTF8'), convert_from(decode('QXZlbnVlIGRlIEpldHRlIDIyNSwgMTA5MCBKZXR0ZSAocG9ydGFpbCB2ZXJ0KQ==','base64'),'UTF8'), true, convert_from(decode('SW5zY3JpcHRpb24gOiAwNDc0IDg1IDc4IDI1IMK3IGluZm9Ad2FrYS11cC5iZQ==','base64'),'UTF8'), convert_from(decode('Q2xhdWRlLCBkJ2FwcsOocyBsZXVyIGNhbGVuZHJpZXIgZCdvY3RvYnJlIDIwMjY=','base64'),'UTF8'), 'femmes'),
(convert_from(decode('V0FLQSBVUA==','base64'),'UTF8'), convert_from(decode('Rm9vdCBlbiBzYWxsZQ==','base64'),'UTF8'), '2026-10-06', convert_from(decode('MThoMzA=','base64'),'UTF8'), convert_from(decode('MjBo','base64'),'UTF8'), convert_from(decode('TGlldSDDoCBjb25maXJtZXIg4oCUIGFwcGVsZXIgV0FLQSBVUA==','base64'),'UTF8'), null, true, convert_from(decode('SW5zY3JpcHRpb24gOiAwNDc0IDg1IDc4IDI1IMK3IGluZm9Ad2FrYS11cC5iZQ==','base64'),'UTF8'), convert_from(decode('Q2xhdWRlLCBkJ2FwcsOocyBsZXVyIGNhbGVuZHJpZXIgZCdvY3RvYnJlIDIwMjY=','base64'),'UTF8'), 'femmes'),
(convert_from(decode('V0FLQSBVUA==','base64'),'UTF8'), convert_from(decode('QXRlbGllciDDqWNyaXR1cmU=','base64'),'UTF8'), '2026-10-07', convert_from(decode('MTBo','base64'),'UTF8'), convert_from(decode('MTJo','base64'),'UTF8'), convert_from(decode('Q2hleiBXQUtBIFVQ','base64'),'UTF8'), convert_from(decode('QXZlbnVlIGRlIEpldHRlIDIyNSwgMTA5MCBKZXR0ZSAocG9ydGFpbCB2ZXJ0KQ==','base64'),'UTF8'), true, convert_from(decode('SW5zY3JpcHRpb24gOiAwNDc0IDg1IDc4IDI1IMK3IGluZm9Ad2FrYS11cC5iZQ==','base64'),'UTF8'), convert_from(decode('Q2xhdWRlLCBkJ2FwcsOocyBsZXVyIGNhbGVuZHJpZXIgZCdvY3RvYnJlIDIwMjY=','base64'),'UTF8'), 'femmes'),
(convert_from(decode('V0FLQSBVUA==','base64'),'UTF8'), convert_from(decode('UmVuZm9yY2VtZW50IG11c2N1bGFpcmU=','base64'),'UTF8'), '2026-10-08', convert_from(decode('MTBo','base64'),'UTF8'), convert_from(decode('MTJo','base64'),'UTF8'), convert_from(decode('Q2hleiBXQUtBIFVQ','base64'),'UTF8'), convert_from(decode('QXZlbnVlIGRlIEpldHRlIDIyNSwgMTA5MCBKZXR0ZSAocG9ydGFpbCB2ZXJ0KQ==','base64'),'UTF8'), true, convert_from(decode('SW5zY3JpcHRpb24gOiAwNDc0IDg1IDc4IDI1IMK3IGluZm9Ad2FrYS11cC5iZQ==','base64'),'UTF8'), convert_from(decode('Q2xhdWRlLCBkJ2FwcsOocyBsZXVyIGNhbGVuZHJpZXIgZCdvY3RvYnJlIDIwMjY=','base64'),'UTF8'), 'femmes'),
(convert_from(decode('V0FLQSBVUA==','base64'),'UTF8'), convert_from(decode('TW9tZW50IGJpZW4tw6p0cmUg4oCUIHN1ciByZW5kZXotdm91cw==','base64'),'UTF8'), '2026-10-12', null, null, convert_from(decode('Q2hleiBXQUtBIFVQ','base64'),'UTF8'), convert_from(decode('QXZlbnVlIGRlIEpldHRlIDIyNSwgMTA5MCBKZXR0ZSAocG9ydGFpbCB2ZXJ0KQ==','base64'),'UTF8'), true, convert_from(decode('UsOpc2VydmF0aW9uIHBhciBtZXNzYWdlIDogMDQ3NCA4NSA3OCAyNQ==','base64'),'UTF8'), convert_from(decode('Q2xhdWRlLCBkJ2FwcsOocyBsZXVyIGNhbGVuZHJpZXIgZCdvY3RvYnJlIDIwMjY=','base64'),'UTF8'), 'femmes'),
(convert_from(decode('V0FLQSBVUA==','base64'),'UTF8'), convert_from(decode('Qm94ZQ==','base64'),'UTF8'), '2026-10-12', convert_from(decode('MTBo','base64'),'UTF8'), convert_from(decode('MTFoMzA=','base64'),'UTF8'), convert_from(decode('Q2hleiBXQUtBIFVQ','base64'),'UTF8'), convert_from(decode('QXZlbnVlIGRlIEpldHRlIDIyNSwgMTA5MCBKZXR0ZSAocG9ydGFpbCB2ZXJ0KQ==','base64'),'UTF8'), true, convert_from(decode('SW5zY3JpcHRpb24gOiAwNDc0IDg1IDc4IDI1IMK3IGluZm9Ad2FrYS11cC5iZQ==','base64'),'UTF8'), convert_from(decode('Q2xhdWRlLCBkJ2FwcsOocyBsZXVyIGNhbGVuZHJpZXIgZCdvY3RvYnJlIDIwMjY=','base64'),'UTF8'), 'femmes'),
(convert_from(decode('V0FLQSBVUA==','base64'),'UTF8'), convert_from(decode('VHJpY290','base64'),'UTF8'), '2026-10-12', convert_from(decode('MTNoMzA=','base64'),'UTF8'), convert_from(decode('MTZo','base64'),'UTF8'), convert_from(decode('Q2hleiBXQUtBIFVQ','base64'),'UTF8'), convert_from(decode('QXZlbnVlIGRlIEpldHRlIDIyNSwgMTA5MCBKZXR0ZSAocG9ydGFpbCB2ZXJ0KQ==','base64'),'UTF8'), true, convert_from(decode('SW5zY3JpcHRpb24gOiAwNDc0IDg1IDc4IDI1IMK3IGluZm9Ad2FrYS11cC5iZQ==','base64'),'UTF8'), convert_from(decode('Q2xhdWRlLCBkJ2FwcsOocyBsZXVyIGNhbGVuZHJpZXIgZCdvY3RvYnJlIDIwMjY=','base64'),'UTF8'), 'femmes'),
(convert_from(decode('V0FLQSBVUA==','base64'),'UTF8'), convert_from(decode('Rm9vdCBlbiBzYWxsZQ==','base64'),'UTF8'), '2026-10-13', convert_from(decode('MThoMzA=','base64'),'UTF8'), convert_from(decode('MjBo','base64'),'UTF8'), convert_from(decode('TGlldSDDoCBjb25maXJtZXIg4oCUIGFwcGVsZXIgV0FLQSBVUA==','base64'),'UTF8'), null, true, convert_from(decode('SW5zY3JpcHRpb24gOiAwNDc0IDg1IDc4IDI1IMK3IGluZm9Ad2FrYS11cC5iZQ==','base64'),'UTF8'), convert_from(decode('Q2xhdWRlLCBkJ2FwcsOocyBsZXVyIGNhbGVuZHJpZXIgZCdvY3RvYnJlIDIwMjY=','base64'),'UTF8'), 'femmes'),
(convert_from(decode('V0FLQSBVUA==','base64'),'UTF8'), convert_from(decode('QXRlbGllciBjcsOpYQ==','base64'),'UTF8'), '2026-10-14', convert_from(decode('MTBo','base64'),'UTF8'), convert_from(decode('MTJo','base64'),'UTF8'), convert_from(decode('Q2hleiBXQUtBIFVQ','base64'),'UTF8'), convert_from(decode('QXZlbnVlIGRlIEpldHRlIDIyNSwgMTA5MCBKZXR0ZSAocG9ydGFpbCB2ZXJ0KQ==','base64'),'UTF8'), true, convert_from(decode('SW5zY3JpcHRpb24gOiAwNDc0IDg1IDc4IDI1IMK3IGluZm9Ad2FrYS11cC5iZQ==','base64'),'UTF8'), convert_from(decode('Q2xhdWRlLCBkJ2FwcsOocyBsZXVyIGNhbGVuZHJpZXIgZCdvY3RvYnJlIDIwMjY=','base64'),'UTF8'), 'femmes'),
(convert_from(decode('V0FLQSBVUA==','base64'),'UTF8'), convert_from(decode('TGVzIGF0ZWxpZXJzIEthcmlidQ==','base64'),'UTF8'), '2026-10-14', convert_from(decode('MTRo','base64'),'UTF8'), convert_from(decode('MTVoMzA=','base64'),'UTF8'), convert_from(decode('TGlldSDDoCBjb25maXJtZXIg4oCUIGFwcGVsZXIgV0FLQSBVUA==','base64'),'UTF8'), null, true, convert_from(decode('SW5zY3JpcHRpb24gOiAwNDc0IDg1IDc4IDI1IMK3IGluZm9Ad2FrYS11cC5iZQ==','base64'),'UTF8'), convert_from(decode('Q2xhdWRlLCBkJ2FwcsOocyBsZXVyIGNhbGVuZHJpZXIgZCdvY3RvYnJlIDIwMjY=','base64'),'UTF8'), 'femmes'),
(convert_from(decode('V0FLQSBVUA==','base64'),'UTF8'), convert_from(decode('SW5zdGFudCB6ZW4=','base64'),'UTF8'), '2026-10-15', convert_from(decode('MTBo','base64'),'UTF8'), convert_from(decode('MTJo','base64'),'UTF8'), convert_from(decode('Q2hleiBXQUtBIFVQ','base64'),'UTF8'), convert_from(decode('QXZlbnVlIGRlIEpldHRlIDIyNSwgMTA5MCBKZXR0ZSAocG9ydGFpbCB2ZXJ0KQ==','base64'),'UTF8'), true, convert_from(decode('SW5zY3JpcHRpb24gOiAwNDc0IDg1IDc4IDI1IMK3IGluZm9Ad2FrYS11cC5iZQ==','base64'),'UTF8'), convert_from(decode('Q2xhdWRlLCBkJ2FwcsOocyBsZXVyIGNhbGVuZHJpZXIgZCdvY3RvYnJlIDIwMjY=','base64'),'UTF8'), 'femmes'),
(convert_from(decode('V0FLQSBVUA==','base64'),'UTF8'), convert_from(decode('TW9tZW50IGJpZW4tw6p0cmUg4oCUIHN1ciByZW5kZXotdm91cw==','base64'),'UTF8'), '2026-10-19', null, null, convert_from(decode('Q2hleiBXQUtBIFVQ','base64'),'UTF8'), convert_from(decode('QXZlbnVlIGRlIEpldHRlIDIyNSwgMTA5MCBKZXR0ZSAocG9ydGFpbCB2ZXJ0KQ==','base64'),'UTF8'), true, convert_from(decode('UsOpc2VydmF0aW9uIHBhciBtZXNzYWdlIDogMDQ3NCA4NSA3OCAyNQ==','base64'),'UTF8'), convert_from(decode('Q2xhdWRlLCBkJ2FwcsOocyBsZXVyIGNhbGVuZHJpZXIgZCdvY3RvYnJlIDIwMjY=','base64'),'UTF8'), 'femmes'),
(convert_from(decode('V0FLQSBVUA==','base64'),'UTF8'), convert_from(decode('Qm94ZQ==','base64'),'UTF8'), '2026-10-19', convert_from(decode('MTBo','base64'),'UTF8'), convert_from(decode('MTFoMzA=','base64'),'UTF8'), convert_from(decode('Q2hleiBXQUtBIFVQ','base64'),'UTF8'), convert_from(decode('QXZlbnVlIGRlIEpldHRlIDIyNSwgMTA5MCBKZXR0ZSAocG9ydGFpbCB2ZXJ0KQ==','base64'),'UTF8'), true, convert_from(decode('SW5zY3JpcHRpb24gOiAwNDc0IDg1IDc4IDI1IMK3IGluZm9Ad2FrYS11cC5iZQ==','base64'),'UTF8'), convert_from(decode('Q2xhdWRlLCBkJ2FwcsOocyBsZXVyIGNhbGVuZHJpZXIgZCdvY3RvYnJlIDIwMjY=','base64'),'UTF8'), 'femmes'),
(convert_from(decode('V0FLQSBVUA==','base64'),'UTF8'), convert_from(decode('VHJpY290','base64'),'UTF8'), '2026-10-19', convert_from(decode('MTNoMzA=','base64'),'UTF8'), convert_from(decode('MTZo','base64'),'UTF8'), convert_from(decode('Q2hleiBXQUtBIFVQ','base64'),'UTF8'), convert_from(decode('QXZlbnVlIGRlIEpldHRlIDIyNSwgMTA5MCBKZXR0ZSAocG9ydGFpbCB2ZXJ0KQ==','base64'),'UTF8'), true, convert_from(decode('SW5zY3JpcHRpb24gOiAwNDc0IDg1IDc4IDI1IMK3IGluZm9Ad2FrYS11cC5iZQ==','base64'),'UTF8'), convert_from(decode('Q2xhdWRlLCBkJ2FwcsOocyBsZXVyIGNhbGVuZHJpZXIgZCdvY3RvYnJlIDIwMjY=','base64'),'UTF8'), 'femmes'),
(convert_from(decode('V0FLQSBVUA==','base64'),'UTF8'), convert_from(decode('Rm9vdCBlbiBzYWxsZQ==','base64'),'UTF8'), '2026-10-20', convert_from(decode('MThoMzA=','base64'),'UTF8'), convert_from(decode('MjBo','base64'),'UTF8'), convert_from(decode('TGlldSDDoCBjb25maXJtZXIg4oCUIGFwcGVsZXIgV0FLQSBVUA==','base64'),'UTF8'), null, true, convert_from(decode('SW5zY3JpcHRpb24gOiAwNDc0IDg1IDc4IDI1IMK3IGluZm9Ad2FrYS11cC5iZQ==','base64'),'UTF8'), convert_from(decode('Q2xhdWRlLCBkJ2FwcsOocyBsZXVyIGNhbGVuZHJpZXIgZCdvY3RvYnJlIDIwMjY=','base64'),'UTF8'), 'femmes'),
(convert_from(decode('V0FLQSBVUA==','base64'),'UTF8'), convert_from(decode('QXRlbGllciDDqWNyaXR1cmUgb3UgY3LDqWE=','base64'),'UTF8'), '2026-10-21', convert_from(decode('MTBo','base64'),'UTF8'), convert_from(decode('MTJo','base64'),'UTF8'), convert_from(decode('Q2hleiBXQUtBIFVQ','base64'),'UTF8'), convert_from(decode('QXZlbnVlIGRlIEpldHRlIDIyNSwgMTA5MCBKZXR0ZSAocG9ydGFpbCB2ZXJ0KQ==','base64'),'UTF8'), true, convert_from(decode('SW5zY3JpcHRpb24gOiAwNDc0IDg1IDc4IDI1IMK3IGluZm9Ad2FrYS11cC5iZQ==','base64'),'UTF8'), convert_from(decode('Q2xhdWRlLCBkJ2FwcsOocyBsZXVyIGNhbGVuZHJpZXIgZCdvY3RvYnJlIDIwMjY=','base64'),'UTF8'), 'femmes'),
(convert_from(decode('V0FLQSBVUA==','base64'),'UTF8'), convert_from(decode('UmVuZm9yY2VtZW50IG11c2N1bGFpcmU=','base64'),'UTF8'), '2026-10-22', convert_from(decode('MTBo','base64'),'UTF8'), convert_from(decode('MTJo','base64'),'UTF8'), convert_from(decode('Q2hleiBXQUtBIFVQ','base64'),'UTF8'), convert_from(decode('QXZlbnVlIGRlIEpldHRlIDIyNSwgMTA5MCBKZXR0ZSAocG9ydGFpbCB2ZXJ0KQ==','base64'),'UTF8'), true, convert_from(decode('SW5zY3JpcHRpb24gOiAwNDc0IDg1IDc4IDI1IMK3IGluZm9Ad2FrYS11cC5iZQ==','base64'),'UTF8'), convert_from(decode('Q2xhdWRlLCBkJ2FwcsOocyBsZXVyIGNhbGVuZHJpZXIgZCdvY3RvYnJlIDIwMjY=','base64'),'UTF8'), 'femmes'),
(convert_from(decode('V0FLQSBVUA==','base64'),'UTF8'), convert_from(decode('RmVzdGl2YWwgTGVzIFNvdXMgRW50ZW5kdS5lLnM=','base64'),'UTF8'), '2026-10-25', null, null, convert_from(decode('TGlldSDDoCBjb25maXJtZXIg4oCUIGFwcGVsZXIgV0FLQSBVUA==','base64'),'UTF8'), null, true, convert_from(decode('SW5zY3JpcHRpb24gOiAwNDc0IDg1IDc4IDI1IMK3IGluZm9Ad2FrYS11cC5iZQ==','base64'),'UTF8'), convert_from(decode('Q2xhdWRlLCBkJ2FwcsOocyBsZXVyIGNhbGVuZHJpZXIgZCdvY3RvYnJlIDIwMjY=','base64'),'UTF8'), 'femmes'),
(convert_from(decode('V0FLQSBVUA==','base64'),'UTF8'), convert_from(decode('TW9tZW50IGJpZW4tw6p0cmUg4oCUIHN1ciByZW5kZXotdm91cw==','base64'),'UTF8'), '2026-10-26', null, null, convert_from(decode('Q2hleiBXQUtBIFVQ','base64'),'UTF8'), convert_from(decode('QXZlbnVlIGRlIEpldHRlIDIyNSwgMTA5MCBKZXR0ZSAocG9ydGFpbCB2ZXJ0KQ==','base64'),'UTF8'), true, convert_from(decode('UsOpc2VydmF0aW9uIHBhciBtZXNzYWdlIDogMDQ3NCA4NSA3OCAyNQ==','base64'),'UTF8'), convert_from(decode('Q2xhdWRlLCBkJ2FwcsOocyBsZXVyIGNhbGVuZHJpZXIgZCdvY3RvYnJlIDIwMjY=','base64'),'UTF8'), 'femmes'),
(convert_from(decode('V0FLQSBVUA==','base64'),'UTF8'), convert_from(decode('Qm94ZQ==','base64'),'UTF8'), '2026-10-26', convert_from(decode('MTBo','base64'),'UTF8'), convert_from(decode('MTFoMzA=','base64'),'UTF8'), convert_from(decode('Q2hleiBXQUtBIFVQ','base64'),'UTF8'), convert_from(decode('QXZlbnVlIGRlIEpldHRlIDIyNSwgMTA5MCBKZXR0ZSAocG9ydGFpbCB2ZXJ0KQ==','base64'),'UTF8'), true, convert_from(decode('SW5zY3JpcHRpb24gOiAwNDc0IDg1IDc4IDI1IMK3IGluZm9Ad2FrYS11cC5iZQ==','base64'),'UTF8'), convert_from(decode('Q2xhdWRlLCBkJ2FwcsOocyBsZXVyIGNhbGVuZHJpZXIgZCdvY3RvYnJlIDIwMjY=','base64'),'UTF8'), 'femmes'),
(convert_from(decode('V0FLQSBVUA==','base64'),'UTF8'), convert_from(decode('VHJpY290','base64'),'UTF8'), '2026-10-26', convert_from(decode('MTNoMzA=','base64'),'UTF8'), convert_from(decode('MTZo','base64'),'UTF8'), convert_from(decode('Q2hleiBXQUtBIFVQ','base64'),'UTF8'), convert_from(decode('QXZlbnVlIGRlIEpldHRlIDIyNSwgMTA5MCBKZXR0ZSAocG9ydGFpbCB2ZXJ0KQ==','base64'),'UTF8'), true, convert_from(decode('SW5zY3JpcHRpb24gOiAwNDc0IDg1IDc4IDI1IMK3IGluZm9Ad2FrYS11cC5iZQ==','base64'),'UTF8'), convert_from(decode('Q2xhdWRlLCBkJ2FwcsOocyBsZXVyIGNhbGVuZHJpZXIgZCdvY3RvYnJlIDIwMjY=','base64'),'UTF8'), 'femmes'),
(convert_from(decode('V0FLQSBVUA==','base64'),'UTF8'), convert_from(decode('Rm9vdCBlbiBzYWxsZQ==','base64'),'UTF8'), '2026-10-27', convert_from(decode('MThoMzA=','base64'),'UTF8'), convert_from(decode('MjBo','base64'),'UTF8'), convert_from(decode('TGlldSDDoCBjb25maXJtZXIg4oCUIGFwcGVsZXIgV0FLQSBVUA==','base64'),'UTF8'), null, true, convert_from(decode('SW5zY3JpcHRpb24gOiAwNDc0IDg1IDc4IDI1IMK3IGluZm9Ad2FrYS11cC5iZQ==','base64'),'UTF8'), convert_from(decode('Q2xhdWRlLCBkJ2FwcsOocyBsZXVyIGNhbGVuZHJpZXIgZCdvY3RvYnJlIDIwMjY=','base64'),'UTF8'), 'femmes'),
(convert_from(decode('V0FLQSBVUA==','base64'),'UTF8'), convert_from(decode('SW5zdGFudCB6ZW4=','base64'),'UTF8'), '2026-10-29', convert_from(decode('MTBo','base64'),'UTF8'), convert_from(decode('MTJo','base64'),'UTF8'), convert_from(decode('Q2hleiBXQUtBIFVQ','base64'),'UTF8'), convert_from(decode('QXZlbnVlIGRlIEpldHRlIDIyNSwgMTA5MCBKZXR0ZSAocG9ydGFpbCB2ZXJ0KQ==','base64'),'UTF8'), true, convert_from(decode('SW5zY3JpcHRpb24gOiAwNDc0IDg1IDc4IDI1IMK3IGluZm9Ad2FrYS11cC5iZQ==','base64'),'UTF8'), convert_from(decode('Q2xhdWRlLCBkJ2FwcsOocyBsZXVyIGNhbGVuZHJpZXIgZCdvY3RvYnJlIDIwMjY=','base64'),'UTF8'), 'femmes'),
(convert_from(decode('V0FLQSBVUA==','base64'),'UTF8'), convert_from(decode('VHJpY290IEAgQ3Jhenk=','base64'),'UTF8'), '2026-10-29', convert_from(decode('MTho','base64'),'UTF8'), convert_from(decode('MjBo','base64'),'UTF8'), convert_from(decode('TGlldSDDoCBjb25maXJtZXIg4oCUIGFwcGVsZXIgV0FLQSBVUA==','base64'),'UTF8'), null, true, convert_from(decode('SW5zY3JpcHRpb24gOiAwNDc0IDg1IDc4IDI1IMK3IGluZm9Ad2FrYS11cC5iZQ==','base64'),'UTF8'), convert_from(decode('Q2xhdWRlLCBkJ2FwcsOocyBsZXVyIGNhbGVuZHJpZXIgZCdvY3RvYnJlIDIwMjY=','base64'),'UTF8'), 'femmes'),
(convert_from(decode('V0FLQSBVUA==','base64'),'UTF8'), convert_from(decode('RXNjYWxhZGU=','base64'),'UTF8'), '2026-10-30', convert_from(decode('MTJo','base64'),'UTF8'), convert_from(decode('MTNoMzA=','base64'),'UTF8'), convert_from(decode('TGlldSDDoCBjb25maXJtZXIg4oCUIGFwcGVsZXIgV0FLQSBVUA==','base64'),'UTF8'), null, true, convert_from(decode('SW5zY3JpcHRpb24gOiAwNDc0IDg1IDc4IDI1IMK3IGluZm9Ad2FrYS11cC5iZQ==','base64'),'UTF8'), convert_from(decode('Q2xhdWRlLCBkJ2FwcsOocyBsZXVyIGNhbGVuZHJpZXIgZCdvY3RvYnJlIDIwMjY=','base64'),'UTF8'), 'femmes');
select jour, titre, debut, fin, lieu, pour_qui from public.activites where asso = convert_from(decode('V0FLQSBVUA==','base64'),'UTF8') and jour >= '2026-10-01' order by jour, debut;
