-- Programme d aout 2026 de WAKA UP, encode d apres leur calendrier (image envoyee par Mag).
-- Texte en base64 : le presse-papier vers l editeur SQL abime les accents.
delete from public.activites where asso = convert_from(decode('V0FLQSBVUA==','base64'),'UTF8') and jour >= '2026-08-01' and jour <= '2026-08-31';
insert into public.activites (asso, titre, jour, debut, fin, lieu, adresse, gratuit, inscription, ajoute_par) values
(convert_from(decode('V0FLQSBVUA==','base64'),'UTF8'), convert_from(decode('Qm94ZQ==','base64'),'UTF8'), '2026-08-03', convert_from(decode('MTBo','base64'),'UTF8'), convert_from(decode('MTFoMzA=','base64'),'UTF8'), convert_from(decode('Q2hleiBXQUtBIFVQ','base64'),'UTF8'), convert_from(decode('QXZlbnVlIGRlIEpldHRlIDIyNSwgMTA5MCBKZXR0ZSAocG9ydGFpbCB2ZXJ0KQ==','base64'),'UTF8'), true, convert_from(decode('SW5zY3JpcHRpb24gOiAwNDc0IDg1IDc4IDI1IMK3IGluZm9Ad2FrYS11cC5iZQ==','base64'),'UTF8'), convert_from(decode('Q2xhdWRlLCBkJ2FwcsOocyBsZXVyIGNhbGVuZHJpZXI=','base64'),'UTF8')),
(convert_from(decode('V0FLQSBVUA==','base64'),'UTF8'), convert_from(decode('VHJpY290','base64'),'UTF8'), '2026-08-03', convert_from(decode('MTNoMzA=','base64'),'UTF8'), convert_from(decode('MTZo','base64'),'UTF8'), convert_from(decode('Q2hleiBXQUtBIFVQ','base64'),'UTF8'), convert_from(decode('QXZlbnVlIGRlIEpldHRlIDIyNSwgMTA5MCBKZXR0ZSAocG9ydGFpbCB2ZXJ0KQ==','base64'),'UTF8'), true, convert_from(decode('SW5zY3JpcHRpb24gOiAwNDc0IDg1IDc4IDI1IMK3IGluZm9Ad2FrYS11cC5iZQ==','base64'),'UTF8'), convert_from(decode('Q2xhdWRlLCBkJ2FwcsOocyBsZXVyIGNhbGVuZHJpZXI=','base64'),'UTF8')),
(convert_from(decode('V0FLQSBVUA==','base64'),'UTF8'), convert_from(decode('Qm94ZQ==','base64'),'UTF8'), '2026-08-17', convert_from(decode('MTBo','base64'),'UTF8'), convert_from(decode('MTFoMzA=','base64'),'UTF8'), convert_from(decode('Q2hleiBXQUtBIFVQ','base64'),'UTF8'), convert_from(decode('QXZlbnVlIGRlIEpldHRlIDIyNSwgMTA5MCBKZXR0ZSAocG9ydGFpbCB2ZXJ0KQ==','base64'),'UTF8'), true, convert_from(decode('SW5zY3JpcHRpb24gOiAwNDc0IDg1IDc4IDI1IMK3IGluZm9Ad2FrYS11cC5iZQ==','base64'),'UTF8'), convert_from(decode('Q2xhdWRlLCBkJ2FwcsOocyBsZXVyIGNhbGVuZHJpZXI=','base64'),'UTF8')),
(convert_from(decode('V0FLQSBVUA==','base64'),'UTF8'), convert_from(decode('VHJpY290','base64'),'UTF8'), '2026-08-17', convert_from(decode('MTNoMzA=','base64'),'UTF8'), convert_from(decode('MTZo','base64'),'UTF8'), convert_from(decode('Q2hleiBXQUtBIFVQ','base64'),'UTF8'), convert_from(decode('QXZlbnVlIGRlIEpldHRlIDIyNSwgMTA5MCBKZXR0ZSAocG9ydGFpbCB2ZXJ0KQ==','base64'),'UTF8'), true, convert_from(decode('SW5zY3JpcHRpb24gOiAwNDc0IDg1IDc4IDI1IMK3IGluZm9Ad2FrYS11cC5iZQ==','base64'),'UTF8'), convert_from(decode('Q2xhdWRlLCBkJ2FwcsOocyBsZXVyIGNhbGVuZHJpZXI=','base64'),'UTF8')),
(convert_from(decode('V0FLQSBVUA==','base64'),'UTF8'), convert_from(decode('QXRlbGllciDDqWNyaXR1cmU=','base64'),'UTF8'), '2026-08-19', convert_from(decode('MTBo','base64'),'UTF8'), convert_from(decode('MTJo','base64'),'UTF8'), convert_from(decode('Q2hleiBXQUtBIFVQ','base64'),'UTF8'), convert_from(decode('QXZlbnVlIGRlIEpldHRlIDIyNSwgMTA5MCBKZXR0ZSAocG9ydGFpbCB2ZXJ0KQ==','base64'),'UTF8'), true, convert_from(decode('SW5zY3JpcHRpb24gOiAwNDc0IDg1IDc4IDI1IMK3IGluZm9Ad2FrYS11cC5iZQ==','base64'),'UTF8'), convert_from(decode('Q2xhdWRlLCBkJ2FwcsOocyBsZXVyIGNhbGVuZHJpZXI=','base64'),'UTF8')),
(convert_from(decode('V0FLQSBVUA==','base64'),'UTF8'), convert_from(decode('SW5zdGFudCB6ZW4=','base64'),'UTF8'), '2026-08-20', convert_from(decode('MTBo','base64'),'UTF8'), convert_from(decode('MTFoMzA=','base64'),'UTF8'), convert_from(decode('Q2hleiBXQUtBIFVQ','base64'),'UTF8'), convert_from(decode('QXZlbnVlIGRlIEpldHRlIDIyNSwgMTA5MCBKZXR0ZSAocG9ydGFpbCB2ZXJ0KQ==','base64'),'UTF8'), true, convert_from(decode('SW5zY3JpcHRpb24gOiAwNDc0IDg1IDc4IDI1IMK3IGluZm9Ad2FrYS11cC5iZQ==','base64'),'UTF8'), convert_from(decode('Q2xhdWRlLCBkJ2FwcsOocyBsZXVyIGNhbGVuZHJpZXI=','base64'),'UTF8')),
(convert_from(decode('V0FLQSBVUA==','base64'),'UTF8'), convert_from(decode('RXNjYWxhZGU=','base64'),'UTF8'), '2026-08-20', convert_from(decode('MTJoMzA=','base64'),'UTF8'), convert_from(decode('MTRo','base64'),'UTF8'), convert_from(decode('Q2hleiBXQUtBIFVQ','base64'),'UTF8'), convert_from(decode('QXZlbnVlIGRlIEpldHRlIDIyNSwgMTA5MCBKZXR0ZSAocG9ydGFpbCB2ZXJ0KQ==','base64'),'UTF8'), true, convert_from(decode('SW5zY3JpcHRpb24gOiAwNDc0IDg1IDc4IDI1IMK3IGluZm9Ad2FrYS11cC5iZQ==','base64'),'UTF8'), convert_from(decode('Q2xhdWRlLCBkJ2FwcsOocyBsZXVyIGNhbGVuZHJpZXI=','base64'),'UTF8')),
(convert_from(decode('V0FLQSBVUA==','base64'),'UTF8'), convert_from(decode('Q2hhbnRzICYgcnl0aG1lcw==','base64'),'UTF8'), '2026-08-21', convert_from(decode('MTdoMzA=','base64'),'UTF8'), convert_from(decode('MTlo','base64'),'UTF8'), convert_from(decode('Q2hleiBXQUtBIFVQ','base64'),'UTF8'), convert_from(decode('QXZlbnVlIGRlIEpldHRlIDIyNSwgMTA5MCBKZXR0ZSAocG9ydGFpbCB2ZXJ0KQ==','base64'),'UTF8'), true, convert_from(decode('SW5zY3JpcHRpb24gOiAwNDc0IDg1IDc4IDI1IMK3IGluZm9Ad2FrYS11cC5iZQ==','base64'),'UTF8'), convert_from(decode('Q2xhdWRlLCBkJ2FwcsOocyBsZXVyIGNhbGVuZHJpZXI=','base64'),'UTF8')),
(convert_from(decode('V0FLQSBVUA==','base64'),'UTF8'), convert_from(decode('Qm94ZQ==','base64'),'UTF8'), '2026-08-24', convert_from(decode('MTBo','base64'),'UTF8'), convert_from(decode('MTFoMzA=','base64'),'UTF8'), convert_from(decode('Q2hleiBXQUtBIFVQ','base64'),'UTF8'), convert_from(decode('QXZlbnVlIGRlIEpldHRlIDIyNSwgMTA5MCBKZXR0ZSAocG9ydGFpbCB2ZXJ0KQ==','base64'),'UTF8'), true, convert_from(decode('SW5zY3JpcHRpb24gOiAwNDc0IDg1IDc4IDI1IMK3IGluZm9Ad2FrYS11cC5iZQ==','base64'),'UTF8'), convert_from(decode('Q2xhdWRlLCBkJ2FwcsOocyBsZXVyIGNhbGVuZHJpZXI=','base64'),'UTF8')),
(convert_from(decode('V0FLQSBVUA==','base64'),'UTF8'), convert_from(decode('VHJpY290','base64'),'UTF8'), '2026-08-24', convert_from(decode('MTNoMzA=','base64'),'UTF8'), convert_from(decode('MTZo','base64'),'UTF8'), convert_from(decode('Q2hleiBXQUtBIFVQ','base64'),'UTF8'), convert_from(decode('QXZlbnVlIGRlIEpldHRlIDIyNSwgMTA5MCBKZXR0ZSAocG9ydGFpbCB2ZXJ0KQ==','base64'),'UTF8'), true, convert_from(decode('SW5zY3JpcHRpb24gOiAwNDc0IDg1IDc4IDI1IMK3IGluZm9Ad2FrYS11cC5iZQ==','base64'),'UTF8'), convert_from(decode('Q2xhdWRlLCBkJ2FwcsOocyBsZXVyIGNhbGVuZHJpZXI=','base64'),'UTF8')),
(convert_from(decode('V0FLQSBVUA==','base64'),'UTF8'), convert_from(decode('QXRlbGllciBjcsOpYQ==','base64'),'UTF8'), '2026-08-26', convert_from(decode('MTBo','base64'),'UTF8'), convert_from(decode('MTJo','base64'),'UTF8'), convert_from(decode('Q2hleiBXQUtBIFVQ','base64'),'UTF8'), convert_from(decode('QXZlbnVlIGRlIEpldHRlIDIyNSwgMTA5MCBKZXR0ZSAocG9ydGFpbCB2ZXJ0KQ==','base64'),'UTF8'), true, convert_from(decode('SW5zY3JpcHRpb24gOiAwNDc0IDg1IDc4IDI1IMK3IGluZm9Ad2FrYS11cC5iZQ==','base64'),'UTF8'), convert_from(decode('Q2xhdWRlLCBkJ2FwcsOocyBsZXVyIGNhbGVuZHJpZXI=','base64'),'UTF8')),
(convert_from(decode('V0FLQSBVUA==','base64'),'UTF8'), convert_from(decode('UmVuZm9yY2VtZW50IG11c2N1bGFpcmU=','base64'),'UTF8'), '2026-08-27', convert_from(decode('MTBo','base64'),'UTF8'), convert_from(decode('MTFoMzA=','base64'),'UTF8'), convert_from(decode('Q2hleiBXQUtBIFVQ','base64'),'UTF8'), convert_from(decode('QXZlbnVlIGRlIEpldHRlIDIyNSwgMTA5MCBKZXR0ZSAocG9ydGFpbCB2ZXJ0KQ==','base64'),'UTF8'), true, convert_from(decode('SW5zY3JpcHRpb24gOiAwNDc0IDg1IDc4IDI1IMK3IGluZm9Ad2FrYS11cC5iZQ==','base64'),'UTF8'), convert_from(decode('Q2xhdWRlLCBkJ2FwcsOocyBsZXVyIGNhbGVuZHJpZXI=','base64'),'UTF8')),
(convert_from(decode('V0FLQSBVUA==','base64'),'UTF8'), convert_from(decode('Q3JhenkgdGlzc2UtcmVpbmVz','base64'),'UTF8'), '2026-08-27', convert_from(decode('MTho','base64'),'UTF8'), convert_from(decode('MjBo','base64'),'UTF8'), convert_from(decode('Q2hleiBXQUtBIFVQ','base64'),'UTF8'), convert_from(decode('QXZlbnVlIGRlIEpldHRlIDIyNSwgMTA5MCBKZXR0ZSAocG9ydGFpbCB2ZXJ0KQ==','base64'),'UTF8'), true, convert_from(decode('SW5zY3JpcHRpb24gOiAwNDc0IDg1IDc4IDI1IMK3IGluZm9Ad2FrYS11cC5iZQ==','base64'),'UTF8'), convert_from(decode('Q2xhdWRlLCBkJ2FwcsOocyBsZXVyIGNhbGVuZHJpZXI=','base64'),'UTF8'));
select jour, titre, debut from public.activites where asso = convert_from(decode('V0FLQSBVUA==','base64'),'UTF8') order by jour, debut;
