-- Programme de SEPTEMBRE 2026 de WAKA UP, encode d apres leur calendrier
-- (image : activite/Septembre-waka.jpeg, deposee par Mag le 02/09/2026).
-- Texte en base64 : le presse-papier vers l editeur SQL abime les accents.
--
-- ATTENTION AUX LIEUX. Trois activites ne disent pas OU elles se passent :
--   Les ateliers Karibu (9), Foot en salle (22 et 29), Tricot @ Crazy (24).
--   Un foot en salle n avait pas lieu avenue de Jette, et @ Crazy designe
--   Crazy tisse-reines, pas WAKA UP. Plutot que d inventer une adresse, ces
--   quatre lignes portent 'Lieu a confirmer' et le telephone : envoyer
--   quelqu un a la mauvaise adresse, c est la version 'lieu' du numero invente.
delete from public.activites where asso = convert_from(decode('V0FLQSBVUA==','base64'),'UTF8') and jour >= '2026-09-01' and jour <= '2026-09-30';
insert into public.activites (asso, titre, jour, debut, fin, lieu, adresse, gratuit, inscription, ajoute_par) values
(convert_from(decode('V0FLQSBVUA==','base64'),'UTF8'), convert_from(decode('SW5zdGFudCB6ZW4=','base64'),'UTF8'), '2026-09-03', convert_from(decode('MTBo','base64'),'UTF8'), convert_from(decode('MTJo','base64'),'UTF8'), convert_from(decode('Q2hleiBXQUtBIFVQ','base64'),'UTF8'), convert_from(decode('QXZlbnVlIGRlIEpldHRlIDIyNSwgMTA5MCBKZXR0ZSAocG9ydGFpbCB2ZXJ0KQ==','base64'),'UTF8'), true, convert_from(decode('SW5zY3JpcHRpb24gOiAwNDc0IDg1IDc4IDI1IMK3IGluZm9Ad2FrYS11cC5iZQ==','base64'),'UTF8'), convert_from(decode('Q2xhdWRlLCBkJ2FwcsOocyBsZXVyIGNhbGVuZHJpZXIgZGUgc2VwdGVtYnJlIDIwMjY=','base64'),'UTF8')),
(convert_from(decode('V0FLQSBVUA==','base64'),'UTF8'), convert_from(decode('TGVzIGF0ZWxpZXJzIEthcmlidQ==','base64'),'UTF8'), '2026-09-09', convert_from(decode('MTRo','base64'),'UTF8'), convert_from(decode('MTVoMzA=','base64'),'UTF8'), convert_from(decode('TGlldSDDoCBjb25maXJtZXIg4oCUIGFwcGVsZXIgV0FLQSBVUA==','base64'),'UTF8'), convert_from(decode('','base64'),'UTF8'), true, convert_from(decode('SW5zY3JpcHRpb24gOiAwNDc0IDg1IDc4IDI1IMK3IGluZm9Ad2FrYS11cC5iZQ==','base64'),'UTF8'), convert_from(decode('Q2xhdWRlLCBkJ2FwcsOocyBsZXVyIGNhbGVuZHJpZXIgZGUgc2VwdGVtYnJlIDIwMjY=','base64'),'UTF8')),
(convert_from(decode('V0FLQSBVUA==','base64'),'UTF8'), convert_from(decode('UmVuZm9yY2VtZW50IG11c2N1bGFpcmU=','base64'),'UTF8'), '2026-09-10', convert_from(decode('MTBo','base64'),'UTF8'), convert_from(decode('MTJo','base64'),'UTF8'), convert_from(decode('Q2hleiBXQUtBIFVQ','base64'),'UTF8'), convert_from(decode('QXZlbnVlIGRlIEpldHRlIDIyNSwgMTA5MCBKZXR0ZSAocG9ydGFpbCB2ZXJ0KQ==','base64'),'UTF8'), true, convert_from(decode('SW5zY3JpcHRpb24gOiAwNDc0IDg1IDc4IDI1IMK3IGluZm9Ad2FrYS11cC5iZQ==','base64'),'UTF8'), convert_from(decode('Q2xhdWRlLCBkJ2FwcsOocyBsZXVyIGNhbGVuZHJpZXIgZGUgc2VwdGVtYnJlIDIwMjY=','base64'),'UTF8')),
(convert_from(decode('V0FLQSBVUA==','base64'),'UTF8'), convert_from(decode('Qm94ZQ==','base64'),'UTF8'), '2026-09-14', convert_from(decode('MTBo','base64'),'UTF8'), convert_from(decode('MTFoMzA=','base64'),'UTF8'), convert_from(decode('Q2hleiBXQUtBIFVQ','base64'),'UTF8'), convert_from(decode('QXZlbnVlIGRlIEpldHRlIDIyNSwgMTA5MCBKZXR0ZSAocG9ydGFpbCB2ZXJ0KQ==','base64'),'UTF8'), true, convert_from(decode('SW5zY3JpcHRpb24gOiAwNDc0IDg1IDc4IDI1IMK3IGluZm9Ad2FrYS11cC5iZQ==','base64'),'UTF8'), convert_from(decode('Q2xhdWRlLCBkJ2FwcsOocyBsZXVyIGNhbGVuZHJpZXIgZGUgc2VwdGVtYnJlIDIwMjY=','base64'),'UTF8')),
(convert_from(decode('V0FLQSBVUA==','base64'),'UTF8'), convert_from(decode('VHJpY290','base64'),'UTF8'), '2026-09-14', convert_from(decode('MTNoMzA=','base64'),'UTF8'), convert_from(decode('MTZo','base64'),'UTF8'), convert_from(decode('Q2hleiBXQUtBIFVQ','base64'),'UTF8'), convert_from(decode('QXZlbnVlIGRlIEpldHRlIDIyNSwgMTA5MCBKZXR0ZSAocG9ydGFpbCB2ZXJ0KQ==','base64'),'UTF8'), true, convert_from(decode('SW5zY3JpcHRpb24gOiAwNDc0IDg1IDc4IDI1IMK3IGluZm9Ad2FrYS11cC5iZQ==','base64'),'UTF8'), convert_from(decode('Q2xhdWRlLCBkJ2FwcsOocyBsZXVyIGNhbGVuZHJpZXIgZGUgc2VwdGVtYnJlIDIwMjY=','base64'),'UTF8')),
(convert_from(decode('V0FLQSBVUA==','base64'),'UTF8'), convert_from(decode('SW5zdGFudCB6ZW4=','base64'),'UTF8'), '2026-09-17', convert_from(decode('MTBo','base64'),'UTF8'), convert_from(decode('MTJo','base64'),'UTF8'), convert_from(decode('Q2hleiBXQUtBIFVQ','base64'),'UTF8'), convert_from(decode('QXZlbnVlIGRlIEpldHRlIDIyNSwgMTA5MCBKZXR0ZSAocG9ydGFpbCB2ZXJ0KQ==','base64'),'UTF8'), true, convert_from(decode('SW5zY3JpcHRpb24gOiAwNDc0IDg1IDc4IDI1IMK3IGluZm9Ad2FrYS11cC5iZQ==','base64'),'UTF8'), convert_from(decode('Q2xhdWRlLCBkJ2FwcsOocyBsZXVyIGNhbGVuZHJpZXIgZGUgc2VwdGVtYnJlIDIwMjY=','base64'),'UTF8')),
(convert_from(decode('V0FLQSBVUA==','base64'),'UTF8'), convert_from(decode('Qm94ZQ==','base64'),'UTF8'), '2026-09-21', convert_from(decode('MTBo','base64'),'UTF8'), convert_from(decode('MTFoMzA=','base64'),'UTF8'), convert_from(decode('Q2hleiBXQUtBIFVQ','base64'),'UTF8'), convert_from(decode('QXZlbnVlIGRlIEpldHRlIDIyNSwgMTA5MCBKZXR0ZSAocG9ydGFpbCB2ZXJ0KQ==','base64'),'UTF8'), true, convert_from(decode('SW5zY3JpcHRpb24gOiAwNDc0IDg1IDc4IDI1IMK3IGluZm9Ad2FrYS11cC5iZQ==','base64'),'UTF8'), convert_from(decode('Q2xhdWRlLCBkJ2FwcsOocyBsZXVyIGNhbGVuZHJpZXIgZGUgc2VwdGVtYnJlIDIwMjY=','base64'),'UTF8')),
(convert_from(decode('V0FLQSBVUA==','base64'),'UTF8'), convert_from(decode('VHJpY290','base64'),'UTF8'), '2026-09-21', convert_from(decode('MTNoMzA=','base64'),'UTF8'), convert_from(decode('MTZo','base64'),'UTF8'), convert_from(decode('Q2hleiBXQUtBIFVQ','base64'),'UTF8'), convert_from(decode('QXZlbnVlIGRlIEpldHRlIDIyNSwgMTA5MCBKZXR0ZSAocG9ydGFpbCB2ZXJ0KQ==','base64'),'UTF8'), true, convert_from(decode('SW5zY3JpcHRpb24gOiAwNDc0IDg1IDc4IDI1IMK3IGluZm9Ad2FrYS11cC5iZQ==','base64'),'UTF8'), convert_from(decode('Q2xhdWRlLCBkJ2FwcsOocyBsZXVyIGNhbGVuZHJpZXIgZGUgc2VwdGVtYnJlIDIwMjY=','base64'),'UTF8')),
(convert_from(decode('V0FLQSBVUA==','base64'),'UTF8'), convert_from(decode('Rm9vdCBlbiBzYWxsZQ==','base64'),'UTF8'), '2026-09-22', convert_from(decode('MTho','base64'),'UTF8'), convert_from(decode('MjBo','base64'),'UTF8'), convert_from(decode('TGlldSDDoCBjb25maXJtZXIg4oCUIGFwcGVsZXIgV0FLQSBVUA==','base64'),'UTF8'), convert_from(decode('','base64'),'UTF8'), true, convert_from(decode('SW5zY3JpcHRpb24gOiAwNDc0IDg1IDc4IDI1IMK3IGluZm9Ad2FrYS11cC5iZQ==','base64'),'UTF8'), convert_from(decode('Q2xhdWRlLCBkJ2FwcsOocyBsZXVyIGNhbGVuZHJpZXIgZGUgc2VwdGVtYnJlIDIwMjY=','base64'),'UTF8')),
(convert_from(decode('V0FLQSBVUA==','base64'),'UTF8'), convert_from(decode('UmVuZm9yY2VtZW50IG11c2N1bGFpcmU=','base64'),'UTF8'), '2026-09-24', convert_from(decode('MTBo','base64'),'UTF8'), convert_from(decode('MTJo','base64'),'UTF8'), convert_from(decode('Q2hleiBXQUtBIFVQ','base64'),'UTF8'), convert_from(decode('QXZlbnVlIGRlIEpldHRlIDIyNSwgMTA5MCBKZXR0ZSAocG9ydGFpbCB2ZXJ0KQ==','base64'),'UTF8'), true, convert_from(decode('SW5zY3JpcHRpb24gOiAwNDc0IDg1IDc4IDI1IMK3IGluZm9Ad2FrYS11cC5iZQ==','base64'),'UTF8'), convert_from(decode('Q2xhdWRlLCBkJ2FwcsOocyBsZXVyIGNhbGVuZHJpZXIgZGUgc2VwdGVtYnJlIDIwMjY=','base64'),'UTF8')),
(convert_from(decode('V0FLQSBVUA==','base64'),'UTF8'), convert_from(decode('VHJpY290IEAgQ3Jhenk=','base64'),'UTF8'), '2026-09-24', convert_from(decode('MTho','base64'),'UTF8'), convert_from(decode('MjBo','base64'),'UTF8'), convert_from(decode('TGlldSDDoCBjb25maXJtZXIg4oCUIGFwcGVsZXIgV0FLQSBVUA==','base64'),'UTF8'), convert_from(decode('','base64'),'UTF8'), true, convert_from(decode('SW5zY3JpcHRpb24gOiAwNDc0IDg1IDc4IDI1IMK3IGluZm9Ad2FrYS11cC5iZQ==','base64'),'UTF8'), convert_from(decode('Q2xhdWRlLCBkJ2FwcsOocyBsZXVyIGNhbGVuZHJpZXIgZGUgc2VwdGVtYnJlIDIwMjY=','base64'),'UTF8')),
(convert_from(decode('V0FLQSBVUA==','base64'),'UTF8'), convert_from(decode('Qm94ZQ==','base64'),'UTF8'), '2026-09-28', convert_from(decode('MTBo','base64'),'UTF8'), convert_from(decode('MTFoMzA=','base64'),'UTF8'), convert_from(decode('Q2hleiBXQUtBIFVQ','base64'),'UTF8'), convert_from(decode('QXZlbnVlIGRlIEpldHRlIDIyNSwgMTA5MCBKZXR0ZSAocG9ydGFpbCB2ZXJ0KQ==','base64'),'UTF8'), true, convert_from(decode('SW5zY3JpcHRpb24gOiAwNDc0IDg1IDc4IDI1IMK3IGluZm9Ad2FrYS11cC5iZQ==','base64'),'UTF8'), convert_from(decode('Q2xhdWRlLCBkJ2FwcsOocyBsZXVyIGNhbGVuZHJpZXIgZGUgc2VwdGVtYnJlIDIwMjY=','base64'),'UTF8')),
(convert_from(decode('V0FLQSBVUA==','base64'),'UTF8'), convert_from(decode('VHJpY290','base64'),'UTF8'), '2026-09-28', convert_from(decode('MTNoMzA=','base64'),'UTF8'), convert_from(decode('MTZo','base64'),'UTF8'), convert_from(decode('Q2hleiBXQUtBIFVQ','base64'),'UTF8'), convert_from(decode('QXZlbnVlIGRlIEpldHRlIDIyNSwgMTA5MCBKZXR0ZSAocG9ydGFpbCB2ZXJ0KQ==','base64'),'UTF8'), true, convert_from(decode('SW5zY3JpcHRpb24gOiAwNDc0IDg1IDc4IDI1IMK3IGluZm9Ad2FrYS11cC5iZQ==','base64'),'UTF8'), convert_from(decode('Q2xhdWRlLCBkJ2FwcsOocyBsZXVyIGNhbGVuZHJpZXIgZGUgc2VwdGVtYnJlIDIwMjY=','base64'),'UTF8')),
(convert_from(decode('V0FLQSBVUA==','base64'),'UTF8'), convert_from(decode('Rm9vdCBlbiBzYWxsZQ==','base64'),'UTF8'), '2026-09-29', convert_from(decode('MTho','base64'),'UTF8'), convert_from(decode('MjBo','base64'),'UTF8'), convert_from(decode('TGlldSDDoCBjb25maXJtZXIg4oCUIGFwcGVsZXIgV0FLQSBVUA==','base64'),'UTF8'), convert_from(decode('','base64'),'UTF8'), true, convert_from(decode('SW5zY3JpcHRpb24gOiAwNDc0IDg1IDc4IDI1IMK3IGluZm9Ad2FrYS11cC5iZQ==','base64'),'UTF8'), convert_from(decode('Q2xhdWRlLCBkJ2FwcsOocyBsZXVyIGNhbGVuZHJpZXIgZGUgc2VwdGVtYnJlIDIwMjY=','base64'),'UTF8')),
(convert_from(decode('V0FLQSBVUA==','base64'),'UTF8'), convert_from(decode('QXRlbGllciBjcsOpYQ==','base64'),'UTF8'), '2026-09-30', convert_from(decode('MTBo','base64'),'UTF8'), convert_from(decode('MTJo','base64'),'UTF8'), convert_from(decode('Q2hleiBXQUtBIFVQ','base64'),'UTF8'), convert_from(decode('QXZlbnVlIGRlIEpldHRlIDIyNSwgMTA5MCBKZXR0ZSAocG9ydGFpbCB2ZXJ0KQ==','base64'),'UTF8'), true, convert_from(decode('SW5zY3JpcHRpb24gOiAwNDc0IDg1IDc4IDI1IMK3IGluZm9Ad2FrYS11cC5iZQ==','base64'),'UTF8'), convert_from(decode('Q2xhdWRlLCBkJ2FwcsOocyBsZXVyIGNhbGVuZHJpZXIgZGUgc2VwdGVtYnJlIDIwMjY=','base64'),'UTF8'));
select jour, titre, debut, lieu from public.activites where asso = convert_from(decode('V0FLQSBVUA==','base64'),'UTF8') and jour >= '2026-09-01' order by jour, debut;
